.github/workflows/main.yml, README.md
In this PR we are adding the first github actions workflow that is tasked to run automatically the tests on each merge to master and on opening PRs from collaborators. 
Acceptance tests are also set to run only one at a time to not interfere with the state of the Auth0 Tenant.
=> DXCDT-39: Add github actions workflows

auth0/data_source_helpers.go, auth0/internal/debug/debug.go, auth0/internal/hash/hash_test.go, auth0/internal/validation/validation.go, auth0/resource_auth0_action.go, auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go, auth0/resource_auth0_global_client.go, auth0/resource_auth0_log_stream_test.go, auth0/resource_auth0_user.go, auth0/resource_data.go, auth0/resource_data_test.go
In this PR we fix some of the linting issues found inside the project after running:
```sh
docker run --rm -v `pwd`:/terraform-provider-auth0 -w /terraform-provider-auth0 golangci/golangci-lint:v1.44.0 golangci-lint run ./...
```
=> Fix some of the linting issues

.goreleaser.yml
We're removing the manifest for now as it seems alexkappa/terraform-provider-auth0 wasn't using it to make the releases due to using v1 of the terraform sdk.
=> Remove terraform-registry-manifest.json reference

auth0/data_source_auth0_client_test.go, auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go, docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md
* Added `signing_keys` to `readClient`
SigningKeys is already supported in [management client](https://github.com/go-auth0/auth0/blob/master/management/client.go), so exposing this.
=> Add Signing Keys to client resource

auth0/resource_auth0_client.go
Marking signing key as sensitive to hide output.
=> mark signing key as sensitive

auth0/resource_auth0_tenant.go
The `auth0_tenant` resource has supported the `default_redirection_uri` for some time (see commit https://github.com/auth0/terraform-provider-auth0/commit/a8d7db403c04d3e17f8f34339dc2f596969ba167). However, whilst this commit added the parameter, tests, and documentation, it didn't actually wire the parameter into the underlying Auth0 API calls (i.e. it's absent from `readTenant` and `buildTenant` in `resource_auth0_tenant.go`) and thus setting this parameter doesn't actually do anything.
This PR adds `default_redirection_uri` into `readTenant` and `buildTenant` and maps it to the `DefaultRedirectionURI` field of `management.Tenant`.
=> Wiring 'default_redirection_uri' parameter in 'auth0_tenant' into Auth0 API call

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, auth0/structure_auth0_connection.go, docs/resources/connection.md
Add a new show_as_button option to be able to show a connection as a button.
This fixes: https://github.com/auth0/terraform-provider-auth0/issues/57. 
Continues from: https://github.com/auth0/terraform-provider-auth0/pull/69. 
=> Add ShowAsButton option for enterprise connections

auth0/resource_auth0_attack_protection.go, auth0/resource_auth0_attack_protection_test.go, docs/resources/attack_protection.md, docs/resources/client.md
This PR accounts for PSAAS environments that don't have the `Stage` property set on the SuspiciousIPThrottling setting. 
We also improving error handling and making it much more robust within the attack_protection resource.
Fixes: https://github.com/auth0/terraform-provider-auth0/issues/85. 
=> [DXCDT-77] Fix attack protection resource for psaas tenants

auth0/data_source_auth0_tenant.go, auth0/data_source_auth0_tenant_test.go, auth0/provider.go, docs/data-sources/tenant.md, example/multiple_environments/README.md, example/multiple_environments/custom/main.tf, example/multiple_environments/custom/versions.tf, example/multiple_environments/modules/admin_console/main.tf, example/multiple_environments/modules/admin_console/versions.tf, example/multiple_environments/prod/main.tf, example/multiple_environments/prod/versions.tf, example/multiple_environments/stage/main.tf, example/multiple_environments/stage/versions.tf
This is a replacement for #84, because I didn't realize changing the branch name would close that PR. :disappointed: 
It addresses the feedback in https://github.com/auth0/terraform-provider-auth0/pull/84#pullrequestreview-916011642, including an added example. The original description is below for posterity:
This change adds a new data source, `auth0_tenant`, which simply returns some helpful information about the current provider configuration. It is particularly helpful when developing a reusable module that expects this provider as an input, because the module may need to know the domain for downstream configuration (e.g. of frontend applications for redirects) or to set up client grants against the management API.
**Note:** Checklist required to be completed before a PR is considered …
=> Add auth0_tenant data source

auth0/resource_auth0_resource_server.go, auth0/resource_auth0_resource_server_test.go
This PR stops ignoring errors when setting resource data within the resource server.
=> DXCDT-98 Stop ignoring errors when setting resource data within the resource server

auth0/data_source_auth0_client.go, auth0/data_source_auth0_client_test.go, auth0/data_source_auth0_global_client_test.go, auth0/resource_auth0_client.go
This PR stops ignoring errors when setting resource data within the client. 
```
Error: 2 errors occurred:
* addons: '': source data must be an array or slice, got map
* mobile: '': source data must be an array or slice, got map
```
This fixes: 
- https://github.com/auth0/terraform-provider-auth0/issues/92
- https://github.com/auth0/terraform-provider-auth0/issues/28
- https://github.com/auth0/terraform-provider-auth0/issues/20
=> DXCDT-94 Stop ignoring errors when setting resource data within the client

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, auth0/structure_auth0_connection.go
This PR stops ignoring errors when setting resource data within the connection.
```
* options.0.password_dictionary: '': source data must be an array or slice, got map
* options.0.password_history: '': source data must be an array or slice, got map
* options.0.totp: '': source data must be an array or slice, got map
* options.0.gateway_authentication: '': source data must be an array or slice, got map
* options.0.idp_initiated: '': source data must be an array or slice, got map
* options.0.validation: '': source data must be an array or slice, got map
* options.0.mfa: '': source data must be an array or slice, got map
* options.0.password_no_personal_info: '': source data must be an array or slice, got map
* options.0.password_complexity_options: '': source data must be an array or slice, …
```
=> DXCDT-95 Stop ignoring errors when setting resource data within the connection

auth0/resource_auth0_prompt.go, auth0/resource_auth0_prompt_custom_text.go, auth0/resource_auth0_prompt_test.go
Stop ignoring errors when setting resource data within prompt.
=> DXCDT-80 Stop ignoring errors when setting resource data within prompt

auth0/resource_auth0_client_grant.go, auth0/resource_auth0_client_grant_test.go, auth0/resource_auth0_custom_domain.go, auth0/resource_auth0_custom_domain_test.go, auth0/resource_auth0_custom_domain_verification.go, auth0/resource_auth0_guardian.go, auth0/resource_auth0_guardian_test.go, auth0/resource_auth0_hook.go, auth0/resource_auth0_hook_test.go, auth0/resource_auth0_log_stream.go
Stop ignoring errors on remaining resources.
=> DXCDT-80 Stop ignoring errors on remaining resources

auth0/resource_auth0_action.go, auth0/resource_auth0_action_test.go
Resolves #103.
- [x ] I have read and agreed to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x ] I have read the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x ] Yes
- [ x] Yes, the description provides enough context for the reviewer to understand what these changes accomplish
- [x ] Not needed
- [ x] Yes, all code changes are intentional and no debugging calls are left over
=> fix: fail fast when action fails to build

auth0/data_source_auth0_client.go, auth0/data_source_auth0_global_client.go, auth0/data_source_auth0_tenant.go, auth0/provider.go, auth0/provider_test.go, auth0/resource_auth0_action.go, auth0/resource_auth0_attack_protection.go, auth0/resource_auth0_branding.go, auth0/resource_auth0_client.go, auth0/resource_auth0_client_grant.go, auth0/resource_auth0_connection.go, auth0/resource_auth0_custom_domain.go, auth0/resource_auth0_custom_domain_verification.go, auth0/resource_auth0_email.go, auth0/resource_auth0_email_template.go, auth0/resource_auth0_global_client.go, auth0/resource_auth0_guardian.go, auth0/resource_auth0_hook.go, auth0/resource_auth0_log_stream.go, auth0/resource_auth0_organization.go, auth0/resource_auth0_prompt.go, auth0/resource_auth0_prompt_custom_text.go, auth0/resource_auth0_resource_server.go, auth0/resource_auth0_role.go, auth0/resource_auth0_rule.go, auth0/resource_auth0_rule_config.go, auth0/resource_auth0_tenant.go, auth0/resource_auth0_trigger_binding.go, auth0/resource_auth0_user.go
With terraform-plugin-sdk@v2 we now have more support for context.Context and Diagnostics. 
- https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#more-support-for-context-context
- https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#support-for-diagnostics
So in this PR we're going ahead and make use of those and remove the deprecated CRUD funcs without the context param in favour of the ones with Context.
No other changes were bundled in this PR. 
=> [3/3] DXCDT-103 Replace resource funcs to use context.Context and Diagnostics

auth0/data_source_auth0_client_test.go, auth0/data_source_auth0_global_client_test.go, auth0/data_source_auth0_tenant_test.go, auth0/provider_test.go, auth0/resource_auth0_action_test.go, auth0/resource_auth0_attack_protection_test.go, auth0/resource_auth0_branding_test.go, auth0/resource_auth0_client_grant_test.go, auth0/resource_auth0_client_test.go, auth0/resource_auth0_connection_test.go, auth0/resource_auth0_custom_domain_test.go, auth0/resource_auth0_custom_domain_verification_test.go, auth0/resource_auth0_email_template_test.go, auth0/resource_auth0_email_test.go, auth0/resource_auth0_global_client_test.go, auth0/resource_auth0_guardian_test.go, auth0/resource_auth0_hook_test.go, auth0/resource_auth0_log_stream_test.go, auth0/resource_auth0_organization_test.go, auth0/resource_auth0_prompt_custom_text_test.go, auth0/resource_auth0_prompt_test.go, auth0/resource_auth0_resource_server_test.go, auth0/resource_auth0_role_test.go, auth0/resource_auth0_rule_config_test.go, auth0/resource_auth0_rule_test.go, auth0/resource_auth0_tenant_test.go, auth0/resource_auth0_trigger_binding_test.go, auth0/resource_auth0_user_test.go, docker-compose.yml
Fix previously configured provider being re-configured warning in tests.
=> [5/5] Fix previously configured provider being re-configured warning in tests

auth0/resource_auth0_log_stream.go, auth0/resource_auth0_log_stream_test.go, example/log_stream/main.tf
This introduces a different schema for the http sink custom headers attribute and fixes its serialization. 
Fixes #119.
=> Fix serialization of log streams with http sink custom headers

auth0/resource_auth0_log_stream.go, auth0/resource_auth0_log_stream_test.go, docs/resources/log_stream.md, example/log_stream/main.tf, go.mod, go.sum
Add filters to log_stream resource.
https://auth0.com/docs/api/management/v2#!/Log_Streams/post_log_streams
Fixes: https://github.com/auth0/terraform-provider-auth0/issues/42
=> [DXCDT-104] Add filters to log_stream resource

CHANGELOG.md, auth0/resource_auth0_client.go, auth0/resource_auth0_client_test.go
Fixes #139 
Fixes issue with the logout property on flattenAddons where we're trying to typecast it always to a map[string]interface{} without checking if it was actually present in the payload.
=> Fix conversion issue flattenAddons func in client resource

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, auth0/structure_auth0_connection.go
=> Fix missing options when importing a connection object

auth0/resource_auth0_custom_domain.go, docs/resources/custom_domain.md
Fixes: https://github.com/auth0/terraform-provider-auth0/issues/45. 
=> Remove deprecated verification_method from custom domain resource

auth0/resource_auth0_tenant.go, auth0/resource_data.go, auth0/structure_auth0_tenant.go
Fixes: #137 
Fixes: #127 
Fixes: #63 
Fixes #54 
Fix auth0 tenant flags so it only sends set values.
=> Fix auth0 tenant flags so it only sends set values

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, auth0/structure_auth0_connection.go, docs/resources/connection.md, go.mod, go.sum
Resolves #156 
Adds support for optional `metadata` field on `auth0_connection` which is supported by Auth0 API.
=> Add support for connection metadata field

auth0/structure_auth0_connection.go
When setting domain_aliases on an ADFS connection the following crash occurs:
> Stack trace from the terraform-provider-auth0_v0.30.3.exe plugin:
> 
> panic: interface conversion: interface {} is *schema.Set, not []interface {}
> 
> goroutine 16 [running]:
> github.com/auth0/terraform-provider-auth0/auth0.Slice({0xcb4b10, 0xc000582560}, {0xb89507, 0xe}, {0x0, 0x0, 0x0})
>         github.com/auth0/terraform-provider-auth0/auth0/resource_data.go:286 +0xe5
> github.com/auth0/terraform-provider-auth0/auth0.expandConnectionOptionsADFS({0xcb4b10, 0xc000582560})
>         github.com/auth0/terraform-provider-auth0/auth0/structure_auth0_connection.go:796 +0x85
> github.com/auth0/terraform-provider-auth0/auth0.expandConnection.func1({0xcb4b10, 0xc000582560})
> …
=> Fix crash with domain_aliases for ADFS

docs/resources/connection.md
Align the indentation of the connection.md examples. A few of them had a mix of tabs and spaces that looked funky
=> Align indentation in connection.md examples

.editorconfig, auth0/resource_auth0_hook.go, auth0/resource_auth0_hook_test.go, auth0/testdata/recordings/TestAccHook.yaml, auth0/testdata/recordings/TestAccHookSecrets.yaml
While taking a look at https://github.com/auth0/terraform-provider-auth0/issues/40, I wasn't able to reproduce the issue with the secrets. I am suspecting that the issue was actually present in the go-auth0 SDK in this func https://github.com/auth0/go-auth0/blob/fcf36e271b507a9af6e2c281013f93181a9d8753/management/hook.go#L143 that eventually got fixed through a newer version. 
However, we made the hook resource implementation more robust with this PR and we are now throwing out warnings in case we encounter secrets that aren't being tracked through terraform. e.g.
```shell
╷
│ Warning: Unexpected Hook Secrets
│
│   with auth0_hook.my_hook,
│   on main.tf line 22, in resource "auth0_hook" "my_hook":
│   22:   secrets = {
│   23:     foo = "foo"
│   24:     car = "car"
│   25:   }
│
│ Found …
```
=> [DXCDT-156] Add warnings for untracked hook secrets

auth0/resource_auth0_connection.go
While investigating https://github.com/auth0/terraform-provider-auth0/issues/108 using the reproducible:
```hcl 
resource "auth0_connection" "sample_connection" {
name     = "sample-connection-issue108"
strategy = "auth0"
options {
enabled_database_customization = "true"
brute_force_protection         = true
import_mode                    = false
disable_signup                 = true
requires_username              = false
custom_scripts                 = {
get_user = <<EOF
function getByEmail (email, callback) {
return callback(new Error("Whoops!"))
}
EOF
}
}
}
```
On subsequent terraform plan's we would constantly get diffs on the password fields as the API assigns certain default values to them. This PR fixes that. 
**Note:** Checklist required to be completed before a PR is considered …
=> Add computed to password* fields in connection resource

auth0/resource_auth0_connection.go, docs/resources/connection.md
Issue #177 highlighted some confusion around configuring scopes for Github connections. The Go SDK appears to perform some conversions so the names of the scopes aren't quite obvious. Adding a validation function here is not possible because the [Terraform provider SDK does not support it for lists and sets](https://github.com/hashicorp/terraform-plugin-sdk/issues/156) so documentation will need to suffice.
=> GitHub connection scopes documentation

auth0/resource_auth0_user.go
As noted in #41 , the Terraform inexplicably converts all user IDs to lower case when writing to state. The specific block of code in question is:
```go
StateFunc: func(s interface{}) string {
return strings.ToLower(s.(string))
},
```
This was added in [this commit](https://github.com/auth0/terraform-provider-auth0/commit/fb0b56b08b81cebc1a6daad541c817ea62e5789e) that was pushed directly to master. It doesn't appear that this code serves any functional purpose and I suspect that it was added in error. Additionally, this line is taken from one of the [Terraform SDK examples](https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#statefunc), which further suggests that it doesn't serve a functional purpose to Auth0.
**Note:** Checklist required to be completed before a PR is …
=> Preserve user ID casing in state

auth0/resource_auth0_connection_test.go, auth0/structure_auth0_connection.go, auth0/testdata/recordings/TestAccConnectionOAuth2.yaml, go.mod, go.sum
As noted in #186 , the `icon_url` property on the `options` object isn't supported in Terraform and gets cleared out every time the configuration applies. 
This PR relies on [this PR](https://github.com/auth0/go-auth0/pull/74) in the Go SDK as a dependency before this can get deployed.
=> Adding `icon_url` to OAuth2 connection types

CHANGELOG.md
=> Add changelog for v0.31.0

auth0/resource_auth0_connection.go, docs/resources/connection.md
Per the code, [app_domain is deprecated](https://github.com/auth0/terraform-provider-auth0/blob/main/auth0/resource_auth0_connection.go#L248-L252). I don't know enough about what `domain` is to be able to add any additional context, though.
=> Remove deprecated options.app_domain in connection resource

Makefile, auth0/provider.go, scripts/release.sh
This PR aims at fixing the request's `User-Agent` field as right now we send the following:
```
"userAgent": "Terraform-Provider-Auth0/dev (Go-Auth0-SDK/0.6.1; Terraform-SDK/1.16.1; Terraform/)",
```
When we should be sending something like:
```
"userAgent": "Terraform-Provider-Auth0/0.31.0 (Go-Auth0-SDK/0.6.1; Terraform-SDK/1.16.1; Terraform/1.2.2)",
```
=> Fix versions in user agent

auth0/resource_auth0_guardian.go, auth0/resource_auth0_guardian_test.go, auth0/testdata/recordings/TestAccGuardian.yaml, auth0/testdata/recordings/TestAccGuardianWebAuthnPlatform.yaml, auth0/testdata/recordings/TestAccGuardianWebAuthnRoaming.yaml, docs/resources/guardian.md
Fixes partially: https://github.com/auth0/terraform-provider-auth0/issues/165, more to follow after this PR. Depends on https://github.com/auth0/go-auth0/pull/83. 
=> [1/X] [DXCDT-175] Add support for webauthn in guardian resource

auth0/resource_auth0_connection.go, auth0/resource_auth0_connection_test.go, auth0/structure_auth0_connection.go, auth0/testdata/recordings/TestAccConnectionTwitter.yaml, go.mod, go.sum
Fixes: https://github.com/auth0/terraform-provider-auth0/issues/224. 
Add support for multiple OAuth2 compatible strategies.
=> [DXCDT-190] Add support for multiple OAuth2 compatible strategies

auth0/resource_auth0_organization.go, auth0/resource_auth0_organization_test.go, auth0/testdata/recordings/TestAccOrganization.yaml
=> Fix issue with not being able to update connections on organizations

auth0/resource_auth0_organization.go, auth0/resource_auth0_organization_test.go, auth0/resource_auth0_user.go, auth0/testdata/recordings/TestAccOrganization.yaml, go.mod, go.sum
=> Fix issue with organization.metadata field not getting set to empty

auth0/resource_auth0_action.go, auth0/resource_auth0_action_test.go, auth0/testdata/recordings/TestAccAction.yaml, auth0/testdata/recordings/TestAccAction_FailedBuild.yaml
=> Fix issue with not being able to update dependencies on actions

auth0/provider.go, auth0/resource_auth0_organization.go, auth0/resource_auth0_organization_connection.go, auth0/resource_auth0_organization_connection_test.go, auth0/resource_auth0_organization_test.go, auth0/testdata/recordings/TestAccOrganization.yaml, auth0/testdata/recordings/TestAccOrganizationConnection.yaml, docs/resources/organization_connection.md, example/organization_connection/main.tf
Splitting the connections out of the organization resource into its own resource, however we keep the old connection sets on the organization until folks have enough time to migrate over. This is done to simplify the internal logic and improve DX. 
=> Add new auth0_organization_connection resource

auth0/resource_auth0_action.go, auth0/resource_auth0_action_test.go, auth0/testdata/recordings/TestAccAction.yaml
Fixes #52 
Although we can already update and create secrets as this was patched before the repo transfer, because we cannot import the values of the secrets we run the risk of erasing the secrets that are found already in the Auth0 Dashboard for the action. 
In this PR we are trying to prevent that from happening in case there are secrets that are not managed through terraform by throwing an error while updating. 
=> Throw error when encountering untracked action secrets

docs/resources/connection.md, internal/provider/resource_auth0_connection.go
Improving the description of the scopes property on the connections.
=> Improve auth0 connection option scopes description

docs/resources/organization_connection.md, examples/resources/auth0_organization_connection/import.sh, internal/provider/resource_auth0_organization_connection.go, internal/provider/resource_auth0_organization_connection_test.go
Raised in https://github.com/auth0/terraform-provider-auth0/issues/299, it appears that we were not able to import correctly the org_conn resource due to the fact that importing doesn't have access to the underlying terraform config, so we can't reuse the org ID and conn ID from there, we need to parse it from the ID and then pass it to the read func so it can find a value when doing `data.Get()`.
=> Fix issue with importing auth0_organization_connection

internal/provider/resource_auth0_prompt.go, internal/provider/resource_auth0_prompt_test.go, test/data/recordings/TestAccPrompt.yaml
https://github.com/auth0/terraform-provider-auth0/issues/264 raises a potential issue with the auth0_prompt resource, however upon trying to reproduce I wasn't able to spot any issues with the bool flags. I ended up slightly refactoring the resource and also adding a test case to ensure the values get pushed and saved correctly.
=> Refactor auth0_prompt resource and add additional test case

internal/provider/data_source_auth0_client.go, test/data/recordings/TestAccDataClientByName.yaml
It was pointed out in https://github.com/auth0/terraform-provider-auth0/issues/267 that the current client data source stops searching based on client name after the first 50 items on the first page of the list. We're fixing that by looping through all the available pages until we find the correct client based on name. Same kind of mechanism already present here: https://github.com/auth0/go-auth0/blob/7fd1c745ba270864d3f4ac5c3284fa52f7fdf8e0/management/client_grant.go#L46
=> Fix data source client to search by name through all available clients

internal/provider/resource_auth0_connection.go, internal/provider/structure_auth0_connection.go, internal/provider/structure_auth0_connection_test.go
As noted in https://github.com/auth0/terraform-provider-auth0/issues/251, out of bound configuration changes are unreported and this unfortunately can cause destructive behavior if we apply the config without checking for unmanaged configuration secrets. These get encrypted and the API will return the values encrypted and not the same as we specify in the config so we can only check for unmanaged keys but not the actual values. We now send an error to the user blocking applying if we find unmanaged config keys.
=> Prevent erasing connection.options.configuration by mistake

CHANGELOG.md
=> Add changelog for v0.37.0

internal/provider/resource_auth0_client.go
This fixes https://github.com/auth0/terraform-provider-auth0/issues/314 by making sure we don't send null to the API in case some fields are not set.
The ideal solution would involve changes in the Go SDK as well by adding types for all the possible Addons instead of having the field as map[string]interface{}, so we could add omitempty json tags. For now this is an intermediary fix before applying these changes to the go SDK.
=> Fix how we expand client.addons.samlp

internal/provider/resource_auth0_hook.go, internal/provider/resource_auth0_hook_test.go, internal/provider/resource_auth0_prompt.go, internal/provider/resource_auth0_prompt_test.go, test/data/recordings/TestAccHook.yaml, test/data/recordings/TestAccHookSecrets.yaml, test/data/recordings/TestAccPrompt.yaml
=> [16/X] Refactor prompts resource to allow for empty fields

internal/provider/resource_auth0_hook.go, internal/provider/resource_auth0_hook_test.go, internal/provider/resource_auth0_log_stream.go, internal/provider/resource_auth0_log_stream_test.go, internal/provider/resource_auth0_prompt.go, internal/provider/resource_auth0_prompt_test.go, internal/provider/resource_auth0_role.go, internal/provider/resource_auth0_role_test.go, internal/provider/resource_auth0_rule.go, internal/provider/resource_auth0_rule_config.go, internal/provider/resource_auth0_rule_config_test.go, internal/provider/resource_auth0_rule_test.go, test/data/recordings/TestAccHook.yaml, test/data/recordings/TestAccHookSecrets.yaml, test/data/recordings/TestAccLogStreamHTTP.yaml, test/data/recordings/TestAccLogStreamSumo.yaml, test/data/recordings/TestAccPrompt.yaml, test/data/recordings/TestAccRole.yaml, test/data/recordings/TestAccRule.yaml, test/data/recordings/TestAccRuleConfig.yaml
=> [14/X] Refactor role and rule resources to allow for empty fields

internal/provider/resource_auth0_custom_domain.go, internal/provider/resource_auth0_custom_domain_verification.go, internal/provider/resource_auth0_hook.go, internal/provider/resource_auth0_hook_test.go, internal/provider/resource_auth0_log_stream.go, internal/provider/resource_auth0_log_stream_test.go, internal/provider/resource_auth0_prompt.go, internal/provider/resource_auth0_prompt_test.go, internal/provider/resource_auth0_role.go, internal/provider/resource_auth0_role_test.go, internal/provider/resource_auth0_rule.go, internal/provider/resource_auth0_rule_config.go, internal/provider/resource_auth0_rule_config_test.go, internal/provider/resource_auth0_rule_test.go, internal/provider/resource_auth0_tenant.go, internal/provider/resource_auth0_tenant_test.go, internal/provider/resource_auth0_user.go, internal/provider/resource_auth0_user_test.go, internal/provider/structure_auth0_tenant.go, test/data/recordings/TestAccHook.yaml, test/data/recordings/TestAccHookSecrets.yaml, test/data/recordings/TestAccLogStreamHTTP.yaml, test/data/recordings/TestAccLogStreamSumo.yaml, test/data/recordings/TestAccPrompt.yaml, test/data/recordings/TestAccRole.yaml, test/data/recordings/TestAccRule.yaml, test/data/recordings/TestAccRuleConfig.yaml, test/data/recordings/TestAccTenant.yaml, test/data/recordings/TestAccUser.yaml, test/data/recordings/TestAccUserChangeUsername.yaml
=> [11/X] Refactor tenant resource to allow for empty fields

internal/provider/resource_auth0_branding.go, internal/provider/resource_auth0_branding_test.go, test/data/recordings/TestAccBranding.yaml
An issue with the branding resource got pointed out in https://github.com/auth0/terraform-provider-auth0/issues/358 after our v0.38.0 release. It turns out we removed by mistake a 404 ignore when fetching the universal login template, so we're adding it back now but also ensuring we properly add tests for that tenant flag check when flattening the struct. 
We are adding additional test cases to cover this part.
=> Ignore 404 error when fetching universal login content in branding

docs/resources/custom_domain.md, internal/provider/resource_auth0_custom_domain.go, internal/provider/resource_auth0_custom_domain_test.go, test/data/recordings/TestAccCustomDomain.yaml
This PR is exposing the `custom_client_ip_header` [option](https://auth0.com/docs/api/management/v2/#!/Custom_Domains/post_custom_domains) for custom domains
=> Add custom_client_ip_header and tls_policy to custom_domain resource

docs/resources/connection.md, examples/resources/auth0_connection/resource_with_oauth2.tf
Small typo in the documentation means code errors as it uses a reserved keyword.
Just a fix to the documentation.
=> Fix up typo: function is a reserved keyword

docs/resources/resource_server.md, internal/provider/resource_auth0_resource_server.go
As pointed out in https://github.com/auth0/terraform-provider-auth0/issues/257, our docs for the RBAC Settings on a resource server are not very clear. This PR aims at improving them.
=> DXCDT-248: Improve resource server RBAC docs

docs/resources/branding_theme.md, internal/provider/resource_auth0_branding_theme.go, internal/provider/resource_auth0_branding_theme_test.go, test/data/recordings/TestAccBrandingTheme.yaml
Change types from int to float32 for increased precision on branding theme fields.
- #333
=> [1/3] DXCDT-243: Improve precision of branding theme fields with float64 instead of int

docs/resources/branding_theme.md, internal/provider/resource_auth0_branding_theme.go, internal/provider/resource_auth0_branding_theme_test.go, internal/provider/resource_auth0_client.go, internal/provider/resource_auth0_client_test.go, internal/provider/structure_auth0_client.go, test/data/recordings/TestAccBrandingTheme.yaml, test/data/recordings/TestAccClientMetadataBehavior.yaml
To correctly remove a key from the `client_metadata` object we need to send it as null to the API. So we're fixing the behavior of the `client_metadata` expand to account for this.
```json
POST /client
{
"client_metadata": {
"foo": "bar",
"faa": "removeMe"
}
}
PATCH /client
{
"client_metadata": {
"foo": "bar",
"faa": null
}
}
GET /client
{
"client_metadata": {
"foo": "bar"
}
}
```
- https://github.com/auth0/go-auth0/pull/120
=> [2/3] DXCDT-234: Fix update behavior of client_metadata

docs/resources/branding_theme.md, docs/resources/connection.md, go.mod, go.sum, internal/provider/resource_auth0_branding_theme.go, internal/provider/resource_auth0_branding_theme_test.go, internal/provider/resource_auth0_client.go, internal/provider/resource_auth0_client_test.go, internal/provider/resource_auth0_connection.go, internal/provider/resource_auth0_connection_test.go, internal/provider/structure_auth0_client.go, test/data/recordings/TestAccBrandingTheme.yaml, test/data/recordings/TestAccClientMetadataBehavior.yaml, test/data/recordings/TestAccConnectionAzureAD.yaml
We are adding validation on `connection.options.identity_api` to only allow "microsoft-identity-platform-v2.0" or "azure-active-directory-v1.0" so it is in line with the error message we get from the API if we pass anything different:
```json
{ "statusCode": 400, "error": "Bad Request", "message": "The identity_api property contains an invalid value. Valid values are 'azure-active-directory-v1.0', 'microsoft-identity-platform-v2.0'", "errorCode": "invalid_body" }
```
- https://github.com/auth0/go-auth0/pull/119
=> [3/3] DXCDT-232: Add validation on identity_api for waad connections

docs/guides/action_triggers.md, docs/guides/quickstart.md, docs/resources/action.md, internal/provider/resource_auth0_action.go, templates/guides/action_triggers.md, templates/guides/quickstart.md
As pointed out in https://github.com/auth0/terraform-provider-auth0/issues/329, it's quite hard to understand what are the correct trigger versions available for an action. We're trying to make this more clear by adding a guide on how to fetch an up to date list of all the triggers and their respective actions.
=> DXCDT-245: Add guide on how to retrieve available action triggers

internal/provider/resource_auth0_email.go, internal/provider/resource_auth0_email_test.go, test/data/recordings/TestAccEmail.yaml, test/data/recordings/TestAccEmailTemplate.yaml
As requested in https://github.com/auth0/terraform-provider-auth0/issues/330 we're improving the DX when managing email providers in the case that one was already configured in the Dashboard and we straight away want to run a terraform apply after writing our configuration, skipping the need of an import.
=> DXCDT-247: Update email provider if already existing when creating it

internal/provider/resource_auth0_client.go, internal/provider/resource_auth0_client_test.go
This PR relaxes the validation rules on `initiate_login_uri` field on `auth0_client` resource to match what the Auth0 API accepts.
* [Issue 388](https://github.com/auth0/terraform-provider-auth0/issues/388)
Tested locally by adding a URL containing a fragment to `initiate_login_uri` and verifying that it both passes validation and actually applies to a client on Auth0.
=> Issue 388: relax validation rules on initiate_login_uri to match API

internal/provider/resource_auth0_email.go
This change is mostly just to be more inline with the API validation so we can alert our users earlier of any issues.
=> [1/4] Add validation to auth0_email attributes

docs/resources/email.md, internal/provider/resource_auth0_email.go, internal/provider/resource_auth0_email_test.go, test/data/recordings/TestAccEmail.yaml
As requested in https://github.com/auth0/terraform-provider-auth0/issues/384, we're adding support for specific email provider settings.
=> [4/4] DXCDT-255: Add settings to auth0_email

internal/value/value.go, internal/value/value_test.go
I was writing a small module to create organizations from a list:
```terraform
module "orgs" {
source                 = "./orgs"
orgs = [
{
name    = "org1-id"
display = "Org1 Name"
logo    = "https://some-url.example"
},
{
name    = "org2-id"
display = "Org2 Name"
logo    = "https://some-url.example"
branding = {
primary    = "#7da5de"
background = "#000000"
}
},
]
}
```
then defined my module as such
```terraform
variable "orgs" {
type = list(object({
name    = string,
display = string,
logo    = string,
branding = optional(object({
primary    = string,
background = string,
}))
}))
}
resource "auth0_organization" "org" {
for_each     = { for org in var.orgs : org.name => org }
name         = each.key
display_name = each.value.display
branding {
logo_url = each.value.logo
colors = { …
```
=> Prevent panic on null values when iterating over map elements

docs/resources/guardian.md, go.mod, go.sum, internal/provider/resource_auth0_guardian.go, internal/provider/resource_auth0_guardian_test.go, internal/provider/structure_auth0_guardian.go, test/data/recordings/TestAccGuardianPush.yaml
This PR adds the ability to manage the selected provider for MultiFactor Push Notification settings through the `auth0_guardian` resource. 
This is needed because without properly selecting the provider to be sns, even if we update the custom app and sns settings, they won't take effect.
=> ESD-25022: Add provider to auth0_guardian.push

internal/mutex/mutex.go, internal/mutex/mutex_test.go, internal/provider/provider.go, internal/provider/resource_auth0_connection_client.go, internal/provider/resource_auth0_organization_connection.go, internal/provider/resource_auth0_organization_member.go
All the association resources are prone to concurrency issues when needing to operate on the same entity. In this PR we are introducing a global mutex to prevent such issues.
=> ESD-25205: Fix concurrency issue in association resources

docs/resources/guardian.md, examples/resources/auth0_guardian/resource.tf, internal/provider/resource_auth0_guardian.go, internal/provider/resource_auth0_guardian_test.go, internal/provider/structure_auth0_guardian.go, test/data/recordings/TestAccGuardian.yaml, test/data/recordings/TestAccGuardianDUO.yaml, test/data/recordings/TestAccGuardianPhone.yaml, test/data/recordings/TestAccGuardianPush.yaml, test/data/recordings/TestAccGuardianWebAuthnPlatform.yaml, test/data/recordings/TestAccGuardianWebAuthnRoaming.yaml
In this PR we are redesigning how the enable/disable mechanism works for mfa types within the `auth0_guardian` resource. 
Previously we used to toggle them on/off implicitly based purely on whether the mfa block was present or not.
E.g.
```terraform
resource "auth0_guardian" "my_guardian" {
policy        = "all-applications"
webauthn_platform {}
}
```
The above would enable WebAuthn with FIDO Device Biometrics MFA.
To provide a better developer experience and to fix a couple of obscure bugs related to the diffing mechanism when out of bounds changes are made (push-notification wasn't showing correctly diffs), we are introducing an `enabled` element to each mfa block. 
E.g. 
```terraform
resource "auth0_guardian" "my_guardian" {
policy        = "all-applications"
webauthn_platform { …
```
=> ESD-25022: Redesign how mfa types get enabled within the guardian resource

docs/resources/guardian.md, internal/provider/resource_auth0_guardian.go, internal/provider/resource_auth0_guardian_test.go, internal/provider/structure_auth0_guardian.go, test/data/recordings/TestAccGuardianPhone.yaml
As noted in https://github.com/auth0/terraform-provider-auth0/issues/433, we erroneously do not allow updating the templates when a custom provider is selected for the guardian resource. This PR aims at fixing that.
=> DXCDT-347: Allow updating templates for phone-message-hook in auth0 guardian

internal/provider/resource_auth0_branding.go, internal/provider/resource_auth0_branding_test.go, test/data/recordings/TestAccBranding.yaml, test/data/recordings/TestAccBranding_WithNoCustomDomainsSet.yaml
When no custom domains are set and we are trying to manage the universal login body template we get an error from the api: `Error: 400 Bad Request: This feature requires at least one custom domain to be configured for the tenant.`. 
The current logic only checks if a tenant flag is set to true, but that's unfortunately flawed. 
In this PR we replace that tenant flag check with checking for available custom domains before managing the universal login template body.
=> DXCDT-348: Manage ul body in branding resource only if custom domains are set

docs/resources/user.md, internal/provider/resource_auth0_user.go
We're trying to always push an update to the Users API with `name`, `given_name`, `family_name` and `nickname` within the payload.
These unfortunately cannot be present in the payload if the connection is not a db or passwordless connection or if the Sync user profile attributes at each login is toggled on. For more info you can read [auth0.com/docs/manage-users/user-accounts/user-profiles/configure-connection-sync-with-auth0](https://auth0.com/docs/manage-users/user-accounts/user-profiles/configure-connection-sync-with-auth0).
- https://github.com/auth0/terraform-provider-auth0/issues/400
=> DXCDT-351: Only send changed fields when updating a user

docs/resources/connection.md, internal/provider/resource_auth0_connection.go, internal/provider/resource_auth0_connection_test.go, internal/provider/structure_auth0_connection.go, test/data/recordings/TestAccConnectionADFS.yaml
As requested in https://github.com/auth0/terraform-provider-auth0/issues/454 we are adding a way to upload the metadata source instead of pointing to a url with the file. 
Various other fields are added as well to the ADFS conn options, that were missing. 
- https://github.com/auth0/terraform-provider-auth0/issues/454
- https://github.com/auth0/go-auth0/pull/161
=> DXCDT-353: Add fed_metadata_xml and other missing fields to adfs connection

internal/auth0/user/resource.go, internal/auth0/user/resource_test.go, internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all user related resources to their own user pkg.
=> DXCDT-360: Move user resources to dedicated pkg

internal/auth0/customdomain/resource.go, internal/auth0/customdomain/resource_test.go, internal/auth0/customdomain/resource_verification.go, internal/auth0/customdomain/resource_verification_test.go, internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all custom domain related resources to their own pkg.
=> DXCDT-360: Move custom domain resources to dedicated pkg

internal/auth0/prompt/resource.go, internal/auth0/prompt/resource_custom_text.go, internal/auth0/prompt/resource_custom_text_test.go, internal/auth0/prompt/resource_test.go, internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all prompt related resources to their own pkg.
=> DXCDT-360: Move prompt resources to dedicated pkg

docs/resources/prompt_custom_text.md, internal/auth0/prompt/resource_custom_text.go
The `status` prompt type was removed from the validation by mistake in https://github.com/auth0/terraform-provider-auth0/pull/506#issuecomment-1446022442. This PR adds it back in. 
- https://github.com/auth0/terraform-provider-auth0/pull/506#issuecomment-1446022442
=> Add missed status prompt type

docs/resources/log_stream.md, internal/auth0/logstream/resource.go
Document the possible `type` values for the auth0 log stream resource.
=> Document the `type` values for the auth0 log stream resource

docs/resources/custom_domain.md, examples/resources/auth0_custom_domain/import.sh
Document how to obtain the custom domain id needed for importing an auth0_custom_domain resource.
=> Document how to obtain the custom domain id needed for importing an auth0_custom_domain resource.

docs/resources/role.md, internal/auth0/role/resource.go
Improves the documentation we have for the `auth0_role.permissions` to explicitly call out that permission name can be referenced from the `auth0_resource_server` scope value property.
- #520
=> issue#520: Update docs for auth0_role permissions

internal/auth0/resourceserver/resource.go
Fixes auth0_resource_server to always expose the ID in the id field instead of the identifier. 
- #530
=> issue#530: Fix auth0_resource_server data source to always return the id

docs/data-sources/connection.md, docs/resources/connection.md, internal/auth0/connection/expand.go, internal/auth0/connection/flatten.go, internal/auth0/connection/resource_test.go, internal/auth0/connection/schema.go, test/data/recordings/TestAccConnection.yaml
This PR adds support for managing the forgot password link within the New Universal Login on the auth0 database connection.
- #486
=> issue#486: Add disable_self_service_change_password to auth0 database connections

docs/data-sources/tenant.md, docs/resources/tenant.md, internal/auth0/tenant/expand.go, internal/auth0/tenant/flatten.go, internal/auth0/tenant/resource.go, internal/auth0/tenant/resource_test.go, test/data/recordings/TestAccTenant.yaml
Add support for `mfa_show_factor_list_on_enrollment` flag on tenant resource.
- #560
=> Add support for `mfa_show_factor_list_on_enrollment` flag on tenant resource

internal/auth0/attackprotection/data_source.go, internal/auth0/branding/data_source.go, internal/auth0/connection/resource_client_import.go, internal/auth0/connection/resource_client_import_test.go, internal/auth0/organization/resource_import.go, internal/auth0/organization/resource_import_test.go, internal/auth0/tenant/data_source.go
This PR changes the `importConnectionClient` function which handles the importing of `auth0_connection_client` resources. When repeatedly importing this resource (like is possible when using a tool like Pulumi) the imported connection client has a new id every time even though it has not changed. This causes the IaC tool to want to recreate the resource, which breaks your environment. Using just the combination of `connection_id:client_id` is unique enough and should be fine to use the identifier for this resource, since I don't think there is a situation where duplicates would exist. (and if they do, that sounds like a misconfiguration)
The only change is that the internal id is now the same each time the same resource is imported.
This can be tested by importing connection clients!
=> Don't override imported connection_client id

MIGRATION_GUIDE.md, docs/resources/user_role.md, examples/resources/auth0_user_role/import.sh, examples/resources/auth0_user_role/resource.tf, internal/auth0/user/resource_role.go, internal/auth0/user/resource_role_test.go, internal/provider/provider.go, templates/resources/user_role.md.tmpl, templates/resources/user_roles.md.tmpl, test/data/recordings/TestAccUserRole.yaml
In this PR we are adding a new auth0_user_roles resource (1:1) to manage the assigned roles on a user.
=> DXCDT-433: Add new auth0_user_role resource

go.mod, go.sum, test/data/recordings/TestAccConnectionCustomSMS.yaml
=> Bump go-auth0 to v0.17.2

internal/auth0/user/resource_permissions.go, internal/auth0/user/resource_permissions_test.go, test/data/recordings/TestAccUserPermissionsImport.yaml
Similar to https://github.com/auth0/terraform-provider-auth0/pull/594, this fixes an import issue with the `auth0_user_permissions` resource.
=> Fix import issue on auth0_user_permissions

internal/auth0/resourceserver/resource_scope.go, internal/auth0/resourceserver/resource_scope_test.go, test/data/recordings/TestAccResourceServerScope.yaml, test/data/recordings/TestAccResourceServerScopeWillNotFailOnCreateIfScopeAlreadyExisting.yaml
In case the scope already exists on the resource server, currently the 1:1 resource for managing scopes will fail on create. This PR prevents that.
=> DXCDT-456: Prevent failure on create if scope already exists in 1:1 resource

docs/resources/connection.md, internal/auth0/connection/expand.go, internal/auth0/connection/flatten.go, internal/auth0/connection/resource_test.go, internal/auth0/connection/schema.go, test/data/recordings/TestAccConnectionAzureAD.yaml
As raised in #587 and #83, the Microsoft Azure AD Connection's `set_user_root_attributes` behavior is different than expected. In order to have the user profile sync on each login, this parameter needs to be omitted from the payload. To do so we need to remove the Computed property from the schema for this value. As well we update our docs to reflect this information. 
- https://github.com/auth0/terraform-provider-auth0/issues/587
- https://github.com/auth0/terraform-provider-auth0/issues/83
=> GH-587: Remove computed property from set_user_root_attributes

CHANGELOG.md
=> Add changelog for v0.48.0

docs/resources/client_credentials.md, internal/auth0/client/resource_credentials.go, internal/auth0/client/resource_credentials_test.go, templates/resources/client_credentials.md.tmpl, test/data/recordings/TestAccClientCredentialsImport.yaml
This PR fixes an import issue with the auth0_client_credentials resource, where the client_id wasn't set into the state within the read func.
=> GH-605: Fix import issue on `auth0_client_credentials` resource

docs/data-sources/organization.md, internal/auth0/organization/data_source.go, internal/auth0/organization/data_source_test.go, internal/auth0/organization/resource_members_test.go, test/data/recordings/TestAccDataSourceOrganizationByID.yaml, test/data/recordings/TestAccDataSourceOrganizationByName.yaml, test/data/recordings/TestAccOrganizationConnections.yaml, test/data/recordings/TestAccOrganizationMembers.yaml
Add members to the `auth0_organization` data source.
- Part 1: https://github.com/auth0/terraform-provider-auth0/pull/614
=> [2/2] DXCDT-457: Add members to the `auth0_organization` data source

internal/auth0/action/resource_trigger_action.go, internal/auth0/connection/resource_client.go, internal/auth0/organization/resource_connection.go, internal/auth0/organization/resource_member.go, internal/auth0/organization/resource_member_roles.go, internal/auth0/prompt/resource_custom_text.go, internal/auth0/resourceserver/resource_scope.go, internal/auth0/role/resource_permission.go, internal/auth0/user/resource_permission.go, internal/schema/importer.go, internal/schema/importer_test.go
This PR renames the old `ImportResourcePairID` func to `ImportResourceGroupID` and it extends its capabilities to be able to accept an aleatory number of attribute names using a variadic string variable and a given separator string so we can also clean up the codebase from redundant import funcs.
=> Refactor import resource group ids logic

CHANGELOG.md
=> Add changelog for v0.49.0

Makefile, internal/acctest/sweep/actions.go, internal/acctest/sweep/custom_domains.go, internal/acctest/sweep/sweep_test.go
The test sweep command is useful to reset a test tenant from any potentially created test resources. In this PR we are enhancing the command by adding an actions sweeper and fixing the custom domains sweeper to correctly remove created custom domains through tests.
=> DXCDT-471: Enhance test sweep command

internal/auth0/organization/resource_connections.go, internal/auth0/organization/resource_members.go
We have a few guards when creating specific resources spread across the provider, this is to ensure we don't overwrite blindly attributes when dealing with Auth0 resources that already exist. However some of these functions had a few issues in the diffing mechanism, please check comments for more details.
These guards are already covered by tests, however further tweaks will follow in another PR.
=> DXCDT-473: Fix how we guard against erasing unwanted changes in resources

internal/auth0/organization/resource_members_test.go, test/data/recordings/TestAccOrganizationMembers.yaml
While ensuring we can reliably run our tests e2e on a real test tenant, we encountered a bug where the organization members resource triggered an error when trying to create the resource with an empty members list. This PR fixes this issue by skipping the API call if the list is empty.
=> DXCDT-471: Fix creating org members when member list is empty

docs/resources/client.md, examples/resources/auth0_client/resource.tf
The `signing_key` property was erroneously added to the `auth0_client` example in #210 instead of the `auth0_connection`. The property was successfully added to the connection resouce in #265 but has erroneously remained in the client resource documentation since. This PR simply removes this property that doesn't actually exist for clients.
This will fix #606 .
Related PRs: #210 , #265 
Related Issue: #606 
N/A.
=> DXCDT-466: Removing `signing_key` from `auth0_client` example

internal/auth0/connection/expand.go, internal/auth0/connection/resource_test.go, internal/auth0/organization/resource_member.go, internal/auth0/role/resource.go, internal/auth0/role/resource_test.go, test/data/recordings/TestAccConnectionGitHub.yaml, test/data/recordings/TestAccRole.yaml
Necessary reordering the add and remove operations returned form `value.Difference()`. It is necessary in cases where non-primitive values are process to remove entities before adding them. The changes here are largely to maintain consistency across the codebase and ensure correct operation.
This change was sparked by a related change in this PR: https://github.com/auth0/terraform-provider-auth0/pull/632/files#diff-8fd4b238e4ecbadc212d2f60d719e9c3666cf53523acecf785f03284f47132bbR83.
Added acceptance test assertions.
=> DXCDT-470: Updating ordering of value.difference, updating tests

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/acctest/acctest.go, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for aws client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [1/X] DXCDT-441: Reintroduce support for aws client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for azure blob client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [2/X] DXCDT-441: Reintroduce support for azure blob client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for azure sb client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [3/X] DXCDT-441: Reintroduce support for azure sb client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for mscrm client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [5/X] DXCDT-441: Reintroduce support for mscrm client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for echosign client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [8/X] DXCDT-441: Reintroduce support for echosign client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for firebase client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [10/X] DXCDT-441: Reintroduce support for firebase client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for sap api client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [15/X] DXCDT-441: Reintroduce support for sap api client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for zoom client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [20/X] DXCDT-441: Reintroduce support for zoom client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for sso integration client addon on the v1 branch after correctly typing them to the new go-auth0 types.
=> [22/X] DXCDT-441: Reintroduce support for samlp client addon

docs/data-sources/client.md, docs/data-sources/global_client.md, docs/resources/client.md, docs/resources/global_client.md, internal/auth0/client/resource.go
Including support for the post_login_promt options for organization_require_behavior in the client resource
- https://github.com/auth0/terraform-provider-auth0/issues/679
- https://auth0.com/changelog, search for Improved Login Flow for SaaS Users
Have tested with client and uses the attribute correctly, all unit and acc tests passing
- [N/A ] All new/changed/fixed functionality is covered by tests (or N/A)
- [ x] I have added documentation for all new/changed functionality (or N/A)
=> Add `post_login_prompt`to available options for `organization_require_behavior` within client resource

docs/resources/client_credentials.md, internal/auth0/client/resource_credentials.go
Fixed docs typo "tonever" -> "to never"
The description for the resource field is split up across multiple lines, making it easy to miss that an extra space is required here. Other field descriptions in the file establish the pattern of putting the space at the end of the first line (examples [1](https://github.com/auth0/terraform-provider-auth0/blame/fa9ef80319d71824cfaba3c8ca17995de741eb0e/internal/auth0/client/resource_credentials.go#L110-L112), [2](https://github.com/auth0/terraform-provider-auth0/blame/fa9ef80319d71824cfaba3c8ca17995de741eb0e/internal/auth0/client/resource_credentials.go#L118-L122)).
I changed the wording in the resource, then ran `make docs`.
- [N/A] All new/changed/fixed functionality is covered by tests (or N/A)
=> Fix missing space in multiline doc for client_credentials

docs/data-sources/connection.md, docs/resources/connection.md, internal/auth0/connection/schema.go
Validation on the `metadata` attribute of the `auth0_connection` resource now allows only keys with length 0-10 and the description shows a max of 10 metadata values. 
I have tested this with the API and you are allowed to:
* Add key lenghts longer then 255
* More then 10 metadata items 
* Values cannot be longer then 255 
I am not sure about the real limits, but it seems that the validation on the attribute does not match the validation on the API.
-
Add connection with following metadata:
```
resource "auth0_connection" "my-connection" {
name           = "my-connection"
display_name   = "My Connection"
metadata = {
longer_then_10_chars = "value"
}
}
```
=> Remove connection metadata key validation

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/security.yml, .github/workflows/sweep.yml
The v4 version of https://github.com/actions/setup-go#caching-dependency-files-and-build-output enables caching by default, however in go 1.20.5 there's a vulnerability that got fixed in 1.20.6, so we need to both make a release and check for vulnerabilities with the latest version of Go.
=> Bump setup-go in gh actions to v4 and disable cache on release/vulncheck

docs/resources/client_grant.md, examples/resources/auth0_client_grant/resource.tf, internal/auth0/client/resource_grant.go, internal/auth0/client/resource_grant_test.go
Renaming from scope to scopes to better indicate that the property is a list of strings.
=> DXCDT-487: Rename scope to scopes in client_grant resource

internal/auth0/connection/resource.go
The schema version for the connection resource on v0.50.0 is set to 2, if we go back and reset this to 0 we will get the following error for users that will try to upgrade:
```
╷
│ Error: Resource instance managed by newer provider version
│
│ The current state of auth0_connection.this was created by a newer provider version than is currently selected. Upgrade the auth0 provider to work with this state.
```
So we increment the version to 3 after removing the schema upgraders to be able to successfully apply the terraform command and refresh the state.
=> Increase schema version for auth0 connection resource

.semgrepignore
This PR adds a `.semgrepignore` manifest file to exclude certain directories and documentation files from being incorrectly flagged by Semgrep. This will help avoid false positive warnings being triggered.
=> ci: Add `.semgrepignore` exclusion manifest

internal/auth0/client/resource_grant.go
Prevent empty string values within scopes attribute of auth0_client_grant resource, so we avoid ending up with a panic.
=> ESD-30646: Add validation to prevent empty string scopes in client grant resource

internal/auth0/client/resource_credentials.go, test/data/recordings/TestAccAllowUpdatingTheClientSecret.yaml, test/data/recordings/TestAccClientAuthenticationMethods.yaml, test/data/recordings/TestAccClientCredentialsImport.yaml, test/data/recordings/TestAccClientGetsCreatedWithIsTokenEndpointIPHeaderTrustedEnabled.yaml
This PR stops requiring the `read:client_keys` permission for reading the `auth0_client_credentials` resource by removing the include fields query param for client_secret. This will be set to a specific value if the permissions is available, otherwise it will be an empty string. 
- https://github.com/auth0/terraform-provider-auth0/issues/774
Tested manually, as our automated tests rely on the full set of permissions to run.
=> DXCDT-518: Stop requiring `read:client_keys` permission for reading the `auth0_client_credentials` resource

internal/auth0/prompt/flatten.go, internal/auth0/prompt/resource_custom_text_test.go, test/data/recordings/TestAccPromptCustomText.yaml
When using Terraform config-driven imports with the `auth0_prompt_custom_text` resource, there can be cases where the `body` property gets generated literally as `"null"`. This occurred because the Management API returns an empty object string literal `"{}"` for unconfigured custom text prompts and would get interpreted somewhere in the Terraform SDK as `nil` which would cause a bit of havoc when marshalling back to a string.
With this PR, the generated custom text prompt looks like this:
```
resource "auth0_prompt_custom_text" "fr_signup" {
body     = "{}"
language = "fr"
prompt   = "signup"
}
```
This is preferred because it matches the output of the Management API.
Added unit tests to enable empty object as body property. Manually verified that config-driven import works as expected.
=> DXCDT-540: Prevent null string literal when importing custom text prompts

docs/resources/client.md, examples/resources/auth0_client/resource.tf
As noted in #813, the `token_endpoint_auth_method` was incorrectly left in an `auth0_client` example when it had been removed from the resource in v1.0.0-beta.1. This removal is also mentioned in the [migration guide](https://github.com/auth0/terraform-provider-auth0/blob/v1/MIGRATION_GUIDE.md#client-authentication-method).
This PR simply removes this property from the example and thus the docs.
- [Related migration guide section](https://github.com/auth0/terraform-provider-auth0/blob/v1/MIGRATION_GUIDE.md#client-authentication-method)
=> Removing `token_endpoint_auth_method` from `auth0_client` example

internal/auth0/connection/expand.go
If there are no connection options set within the config and thus the options block missing, there's no reason to try passing through unconfigurable connection options as the options field will get omitted in the PATCH.
=> Skip passing through connection options if none in config

docs/guides/generate_terraform_config.md, templates/guides/generate_terraform_config.md
One piece of feedback received on auto-generating TF configuration is that it isn't well defined that the Auth0 domains for the TF provider and Auth0 CLI need to match. This relationship was supposed to be implied but now made more explicit through this PR.
This accompanies a [PR in the Auth0 CLI](https://github.com/auth0/auth0-cli/pull/858) that enforces the domain match through code.
- [Related PR](https://github.com/auth0/auth0-cli/pull/858)
=> Emphasize domain-match in TF generate guide

internal/auth0/tenant/flatten.go, internal/auth0/tenant/flatten_test.go, internal/auth0/tenant/resource.go
Sometimes when importing a `auth0_tenant` resource, the `idle_session_lifetime` field gets set to zero. Normally this isn't such a problem because subsequent plans or applies will have this value set to the default value of 72. However, the Auth0 CLI's `auth0 tf generate` command will get hung up on the zero value because it violates the schema's validation. This default is necessary because not all tenants will have the `idle_session_lifetime` value set, particularly if it is a new tenant.
- [TF Generate Command - Auth0 CLI](https://auth0.github.io/auth0-cli/auth0_terraform_generate.html)
Manual verification on a new tenant. Difficult to add to acceptance tests because our testing tenants will always have this value set; it is important to have it _not_ set for testing.
=> Setting default `idle_session_lifetime` on tenant import

docs/resources/connection_clients.md, templates/resources/connection_clients.md.tmpl
The documentation for `auth0_connection_clients` was slightly incorrect — seems like the notice at the top was copied from `auth0_connection_client`. This fixes that notice to be accurate.
=> Fix copy-paste error in `connection_clients` docs

internal/auth0/connection/expand.go
Prevent panic when checking for db config secrets. This could happen when the connection resource does not have any optiosn block defined and we are trying to update it.
=> Prevent panic when checking for db config secrets

docs/data-sources/tenant.md, docs/resources/tenant.md, internal/auth0/tenant/expand.go, internal/auth0/tenant/flatten.go, internal/auth0/tenant/resource.go, internal/auth0/tenant/resource_test.go, test/data/recordings/TestAccTenant.yaml
Adds support for the `customize_mfa_in_postlogin_action` tenant setting
=> DXCDT-563: Add support for `customize_mfa_in_postlogin_action` tenant setting

internal/auth0/branding/resource.go
This PR changes the logic within the delete func of the branding resource to allow free tier tenants to delete the resource as well. Free tier tenants won't have custom domains functionality enabled and at the moment we check if any are set on the tenant to be able to remove the universal login page template.
- #853
=> GH-853: Allow deleting branding resource even on free tenants

docs/resources/action.md, internal/auth0/action/resource.go, templates/resources/action.md.tmpl
As noted in #860, users are having issues managing their action secrets out-of-band through the `ignore_changes` block. However, this doesn't result in the expected behavior and secrets can still be deleted in the process. This PR updates the documentation very clear that secrets and dependencies cannot be managed out-of-band. In short, this is because the provider cannot discern between intentionally empty set of secrets and ignoring secrets by omission.
Related Github Issue: https://github.com/auth0/terraform-provider-auth0/issues/860#issuecomment-1768203036
N/A.
=> Documenting limitation of managing action secrets out-of-bound

docs/resources/action.md, internal/auth0/action/expand.go, internal/auth0/action/resource.go, templates/resources/action.md.tmpl, test/data/recordings/TestAccAction.yaml
This PR adds the data.HasChange check for action secrets and dependencies, so they don't always get sent to the API if no changes were needed.
=> Add HasChange check to action secrets and dependencies

internal/auth0/organization/resource_member.go, test/data/recordings/TestAccDataSourceOrganization.yaml, test/data/recordings/TestAccOrganizationConnection.yaml, test/data/recordings/TestAccOrganizationConnections.yaml, test/data/recordings/TestAccOrganizationMember.yaml, test/data/recordings/TestAccOrganizationMemberRole.yaml, test/data/recordings/TestAccOrganizationMemberRoles.yaml, test/data/recordings/TestAccOrganizationMembers.yaml
- Fix pagination for importing or creating `auth0_organization_member` to handle organizations with more than 50 members (GH-925)
This pull request aims to enhance pagination functionality for importing or creating `auth0_organization_member` by addressing organizations with more than 50 members. We're transitioning from offset pagination, which has a limit of 1000 entries, to checkpoint pagination to ensure efficient retrieval of organization members beyond this limit.
Offset pagination retrieves data by specifying the number of items to skip and the number of items to return. However, its limitation of 1000 entries can lead to inefficient data retrieval for larger datasets. Checkpoint pagination, introduced here, offers a more efficient alternative, especially when dealing with a large …
=> (GH-925) Fix pagination for auth0_organization_member import/Create limit

docs/data-sources/tenant.md, docs/resources/tenant.md, internal/auth0/tenant/resource.go
- Reintroduce and Deprecate the `require_pushed_authorization_requests` Flag to Avoid Breaking Changes
=> Reintroduce and Deprecate `require_pushed_authorization_requests` Flag to Avoid Breaking Changes

Makefile, docs/data-sources/connection.md, docs/resources/connection.md, go.mod, go.sum, internal/acctest/template.go, internal/auth0/connection/expand.go, internal/auth0/connection/flatten.go, internal/auth0/connection/resource_test.go, internal/auth0/connection/schema.go, test/data/recordings/TestAccClientAuthenticationMethods.yaml, test/data/recordings/TestAccConnectionOptionsAttrEmail.yaml, test/data/recordings/TestAccConnectionOptionsAttrInactiveSignUpNegative.yaml, test/data/recordings/TestAccConnectionOptionsAttrNoActiveNegative.yaml, test/data/recordings/TestAccConnectionOptionsAttrPhoneNumber.yaml, test/data/recordings/TestAccConnectionOptionsAttrSetValidationNegative.yaml, test/data/recordings/TestAccConnectionOptionsAttrUserName.yaml, test/data/recordings/TestAccConnectionOptionsAttrUserNameNegative.yaml
1. Added schema updates to ```ConnectionOptions``` and included ```attributes``` and ```precedence```
2. Added corresponding expand and flatten logic.
3. Added relevant test cases to expand and flatten nested structs.
Required changes have been made in line with the [documentation here](https://oktawiki.atlassian.net/wiki/spaces/DXSDK/pages/3009480856/Implementation+of+Phone+Number+as+Identifiers+on+SDK+-+GO-auth0)
[Create a connection with attributes](https://auth0.com/docs/api/management/v2/connections/post-connections)
Body Params: options-> attributes 
```make test FILTER= TestAccConnectionOptionsAttr```
Relevant test cases and their recordings have been added to ensure changes as described above.
All created resources are cleaned up after the assertions are completed.
**- …
=> Add support for ```attributes``` and ```precedence``` to ConnectionOptions & ```phone_number``` to SignupRequest. 

internal/auth0/connection/schema.go
The precedence field is a slice which can either have a length of 0 or 3. That means if specified all three of `email, phone_number, username` must be specified or none. 
Added this patch such that MinItems can be 0 also.
=> Patch: Removed MinItems validation for precedence on Connection Resource

docs/resources/connection.md, examples/resources/auth0_connection/resource_with_azure_ad.tf, go.mod, go.sum, internal/auth0/connection/expand.go, internal/auth0/connection/flatten.go, internal/auth0/connection/resource_test.go, internal/auth0/connection/schema.go, test/data/recordings/TestAccConnectionAzureAD.yaml
Add Support for `user_id_attribute` to `auth0_connection` `options` attribute for AzureAD connections (strategy="waad")
Issue: https://github.com/auth0/terraform-provider-auth0/issues/1006
=> Add user_id_attribute support to AzureAD connection options

internal/auth0/prompt/resource_screen_partial.go, internal/auth0/prompt/resource_screen_partial_test.go, test/data/recordings/TestAccPromptScreenPartial.yaml
- Ensure Removal of Insertion Points in `auth0_prompt_screen_partial` Resource
- [Put Partials API Documentation](https://auth0.com/docs/api/management/v2/prompts/put-partials)
- Performed manual testing to verify the removal of insertion points.
- Added automated test cases to ensure correct behaviour when insertion points are removed.
=> PATCH: Ensure Removal of Insertion Points in `auth0_prompt_screen_partial` Resource

internal/auth0/organization/data_source.go, internal/auth0/organization/data_source_test.go, test/data/recordings/TestAccDataSourceOrganizationInsufficientScope.yaml
The `auth0_organization` data source retrieves a list of connections, members, and client grants for a given organization. However, the client grants and organization association feature is only available to limited users. As a result, an empty slice of client grants is returned for tenants that do not have access to this feature.
---
- Implemented graceful handling for tenants that do not have access to the client grants feature.
- When the `auth0_organization` data source is queried by such tenants, an empty slice is returned for the client grants, ensuring that the data source works without errors for all users, even those without this feature.
N/A
- Added a negative test case that runs against a tenant with insufficient scopes or access to the client grants feature.
- Verified that …
=> PATCH: Add graceful error handling for `auth0_organization` data source when using client grants

internal/provider/provider.go
Added ConfigureContextFunc which checks if `AUTH0_DOMAIN`, `AUTH0_CLIENT_ID` and `AUTH0_CLIENT_SECRET` are configured before planning.
Addressed https://github.com/auth0/terraform-provider-auth0/issues/1023
=> Added a check on provider's configuration for required env vars

internal/config/config.go, internal/config/config_test.go, internal/provider/provider.go
Moved checking required env variables from ConfigureContextFunc to when the provider actually get configured in `ConfigureProvider` during the planning step.
This allows picking variable which might be declared in the tf file itself 
```tf
provider "auth0" {
domain        = "<domain>"
client_id     = "<client-id>"
client_secret = "<client-secret>"
debug         = "<debug>"
}
```
The above is not recommended and use of env variables is advised.
=> Added explicit check for handling missing env variables for login

docs/resources/flow_vault_connection.md, internal/auth0/flow/expand.go, internal/auth0/flow/flatten.go, internal/auth0/flow/resource_vault_connection.go
The `setup` attribute in `auth0_flow_vault_connection` is a write-only field and is not returned as part of Vault.GetConnection. Hence updated the expand/flatten to handle the same.
Also, `ready` attribute is a read-only field so update the schema and marked it as a `Computed` field.
https://github.com/auth0/terraform-provider-auth0/issues/1098
=> PATCH: update `setup` attribute schema for `auth0_flow_vault_connection`

docs/data-sources/connection.md, docs/resources/connection.md, internal/auth0/connection/expand.go, internal/auth0/connection/flatten.go, internal/auth0/connection/resource_test.go, internal/auth0/connection/schema.go
Added the `enabled` flag for options param
Closes https://github.com/auth0/terraform-provider-auth0/issues/971
=> Added missing enabled field to options param connections

docs/resources/connection.md, internal/auth0/connection/schema.go
Added support for `set_user_root_attributes` to be set as `never_on_login `
Closes https://github.com/auth0/terraform-provider-auth0/issues/1121
=> Support never_on_login as allowed value for set_user_root_attributes

docs/resources/prompt_screen_renderer.md, examples/resources/auth0_prompt_screen_renderer/resource.tf
- Removed the unsupported context_configuration `transaction.connection.metadata`
- Updated the format for suffixing the `untrusted_data.authorization_params.ext-` field in context_configuration
=> Update example of auth0_prompt_screen_renderer

CHANGELOG.md
ENHANCEMENTS:
- Support `password reset by otp code` email template and `verification_method` field in connection schema. ([#1113](https://github.com/auth0/terraform-provider-auth0/pull/1113/))
- Update workflow to install terraform manually since ubuntu image has removed it ([#1116](https://github.com/auth0/terraform-provider-auth0/pull/1116/))
- Support never_on_login as an allowed value for set_user_root_attributes ([#1123](https://github.com/auth0/terraform-provider-auth0/pull/1123/))
BUG FIXES:
- Fix: Dynamic block for action.Secrets and iterates via k/v ([#1115](https://github.com/auth0/terraform-provider-auth0/pull/1115/))
- Fix: IdP-initiated SSO Behavior by adding the missing enabled field to options param connections ([#1105](https://github.com/auth0/terraform-provider-auth0/pull …
=> Add changelog for 1.10.0

internal/auth0/action/expand.go, internal/auth0/action/flatten.go, internal/auth0/client/expand.go, internal/auth0/client/flatten.go, internal/auth0/client/resource_test.go, test/data/recordings/TestAccClientMobile.yaml, test/data/recordings/TestAccDataClientByName.yaml
1. `custom-token-exchange` trigger does not support node18-actions as runtime. It only supports node18 and node22. With the present terraform configuration which manipulated node18 input to node18-actions, it was practically impossible to create an action for this trigger with node18 as runtime. A required clause was added to support this and maintain the same functionality for other triggers.
2. Missing expand/flatten rules where added for auth0_client `token_exchange` param
=> Added flatten/expand for token_exchange

internal/auth0/customdomain/data_source.go, internal/auth0/customdomain/data_source_test.go, test/data/recordings/TestAccDataSourceCustomDomain.yaml
At present, a tenant only allows a single custom domain.
The `auth0_custom_domain` communicates to `/custom-domains` endpoint but when returned a slice with 0 items, it doesn't correctly handle this and causes the provider to crash.
Updated this logic to throw an appropriate error when no custom domain is configured.
Closed #1213 
Relevant test cases have been updated and re-recorded.
=> Added validation on `auth0_custom_domain`

CHANGELOG.md
ENHANCEMENTS:
- `resource/auth0_prompt_screen_renderer`: Add support for 14 new screens ([#1226](https://github.com/auth0/terraform-provider-auth0/pull/1226/))
- Add support for dynamic credentials while configuring the provider ([#1172](https://github.com/auth0/terraform-provider-auth0/pull/1172/))  
BUG FIXES:
- `resource/auth0_branding`: Allow setting `font_url` as null ([#1222](https://github.com/auth0/terraform-provider-auth0/pull/1222/)) 
- `resource/auth0_client`: Allow setting `encryption_key` as null ([#1221](https://github.com/auth0/terraform-provider-auth0/pull/1221/))
=> Add changelog for 1.17.0

internal/auth0/connection/data_source_scim_test.go, internal/auth0/connection/expand.go, internal/auth0/connection/resource_scim_test.go, internal/auth0/organization/resource_connections_test.go, test/data/recordings/TestAccDataSCIMConfiguration.yaml, test/data/recordings/TestAccOrganizationConnection.yaml, test/data/recordings/TestAccOrganizationConnections.yaml, test/data/recordings/TestAccSCIMConfiguration.yaml
Sometime in October 2023, the behavior of the Auth0 API changed. It used to automatically set the scopes `openid` and `profile` for all new Okta Workforce enterprise connections (the `okta` strategy).
The API simply stopped doing that - there is no docs to support this claim other than evidence (personal and other folks in the linked GitHub issue).
This change makes it so that the engineer making changes will see the error instead of their customers...
Creating an Okta workforce without the `openid` claim results in anyone trying to authenticate with this connection seeing the error:
```
Cannot read properties of undefined (reading 'trim')
```
Here's a screenshot from one of my very-unhappy customers:
Closes https://github.com/auth0/terraform-provider-auth0/issues/852
N/A
=> Make "scopes" required for Okta Workforce Connections

docs/resources/resource_server_scope.md, docs/resources/resource_server_scopes.md, examples/resources/auth0_resource_server_scope/resource.tf, examples/resources/auth0_resource_server_scopes/resource.tf
Until the migration we had to put the `ignore_changes = [scopes]` block on the `auth0_resource_server` 
Updated the docs to remove it from examples.
Closes #994
=> Updated examples and docs for `auth0_resource_server`

CHANGELOG.md
FEATURES:
- `resource/auth0_client`: Add support for the `flexible_mappings` field to handle complex key structures (e.g., slice-based keys) ([#1253](https://github.com/auth0/terraform-provider-auth0/pull/1253/))
- `resource/auth0_client`: Add support to configure `allow_refresh_token` in `session_transfer` ([#1246](https://github.com/auth0/terraform-provider-auth0/pull/1246/))
- Add support for Auth0 CLI-based authentication via the `cli_login` flag ([#1242](https://github.com/auth0/terraform-provider-auth0/pull/1242/))
ENHANCEMENTS:
- `resource/auth0_prompt_screen_renderer`: Add support for 21 new screens ([#1249](https://github.com/auth0/terraform-provider-auth0/pull/1249/))
BUG FIXES:
- `resource/auth0_client`: Update `custom_headers` to a set of objects (maps with `header`/`value` …
=> Add changelog for v1.20.0

CHANGELOG.md
BUG FIXES:
- `resource/auth0_prompt_screen_renderer`: Remove unreleased screens for ACUL  ([#1257](https://github.com/auth0/terraform-provider-auth0/pull/1257))
=> Add changelog for v1.20.1

internal/auth0/logstream/flatten.go, internal/auth0/logstream/resource.go
At times, the API returns a computed value for `filters` on `auth0_log_stream` resource. An example case is when setting the value for `is_priority`.
Hence updated the schema to meet this requirement
Closes #1296
=> fix:  make `filters` computed for auth0_log_stream

CHANGELOG.md
BUG FIXES:
- `resource/auth0_user` - Add support for passing `custom_domain_header` ([#1316](https://github.com/auth0/terraform-provider-auth0/pull/1316))
- `data_source/auth0_user` - Add support for passing `custom_domain_header` ([#1316](https://github.com/auth0/terraform-provider-auth0/pull/1316))
- Add support to globally configure `custom_domain_header` ([#1316](https://github.com/auth0/terraform-provider-auth0/pull/1316))
=> Add changelog for v1.24.1

internal/auth0/connection/resource_client.go
This pull request adds pagination via `management.ConnectionEnabledClientList.Next()` to `readConnectionClient` method so that all Clients are returned to read from.
I believe this fixes #1321, or is at least adjacent.
This was first brought to our attention at Pulumi via https://github.com/pulumi/pulumi-auth0/issues/909, and we thought we'd bring the fix upstream to you.
Testing is difficult for this one, because it involves API calls. Our free-tier auth0 instance doesn't support creating more than 10 clients, and this is an error that shows up when the number of clients is greater than the default number of clients per page returned by the Auth0 API (which is 50 [per the docs](https://auth0.com/docs/api/management/v2/connections/get-connection-clients)).
I did build this provider with a …
=> Add pagination to auth0_connection_client to avoid error on Create

internal/auth0/connection/data_source.go, internal/auth0/connection/resource_client.go, internal/auth0/connection/resource_clients.go
The present implementation was missing Pagination and hence for higher number of client, it'd only fetch the initial defaults.
Added required updates to the data source.
Tested with test suite and recordings.
=> fix: Retrieve all clients for a connection via Pagination query

docs/resources/email_template.md, examples/resources/auth0_email_template/import.sh, internal/auth0/email/resource_template.go
- Added a new template option `async_approval` to the `EmailTemplate` type.
- Updated validation and documentation comments to reflect the new template option.
- Verified that `async_approval` is accepted when creating or updating email templates.
- Confirmed that all existing templates (`verify_email`, `reset_email`, etc.) continue to work correctly.
=> feat(email): add  template option to EmailTemplate
