- auth0/data_source_auth0_client.go
- auth0/data_source_auth0_client_test.go
- auth0/data_source_auth0_global_client.go
- auth0/data_source_auth0_global_client_test.go
- auth0/provider.go
- auth0/provider_test.go
- auth0/resource_auth0_guardian.go
- auth0/resource_auth0_guardian_test.go
- auth0/resource_data_test.go
- docs/datasources/client.md
- docs/datasources/global_client.md
- docs/index.md
- docs/resources/client.md
- docs/resources/guardian.md
- docs/resources/user.md
This PR simply brings in the latest commits from alexkappa/terraform-provider-auth0 and fixes small issues from merge conflicts.
> Bring in latest commits from alexkappa/terraform-provider-auth0

- CHANGELOG.md
Adding a changelog for this repo as well as the anticipated changes for our upcoming 0.27.0 release.
> Adding and updating changelog for 0.27.0

- .github/workflows/release.yml
- .goreleaser.yml
In this PR we are adding a github action to execute whenever we create a new tag, so it can build the release binaries with [goreleaser](https://github.com/goreleaser/goreleaser).
> Add release workflow

- CHANGELOG.md
> Update changelog for v0.27.1

- CHANGELOG.md
> Update changelog for v0.28.0

- auth0/resource_auth0_email.go
- auth0/resource_auth0_email_template.go
- auth0/resource_auth0_email_template_test.go
- auth0/resource_auth0_email_test.go
This PR stops ignoring errors when setting resource data within the emails.
> DXCDT-99 Stop ignoring errors when setting resource data within the email

- auth0/resource_auth0_user.go
- auth0/resource_auth0_user_test.go
This PR stops ignoring errors when setting resource data within the user.
> DXCDT-97 Stop ignoring errors when setting resource data within the user

- auth0/resource_auth0_tenant.go
- auth0/resource_auth0_tenant_test.go
- auth0/structure_auth0_tenant.go
This PR stops ignoring errors when setting resource data within the tenant.
> DXCDT-96 Stop ignoring errors when setting resource data within the tenant

- auth0/resource_auth0_action.go
- auth0/resource_auth0_action_test.go
- auth0/resource_auth0_trigger_binding.go
- auth0/resource_auth0_trigger_binding_test.go
Stop ignoring errors when setting resource data within the action
> DXCDT-100 Stop ignoring errors when setting resource data within the action

- CHANGELOG.md
> Add changelog for v0.29.0

- README.md
Add full license report in readme
> Add full license report in readme

- auth0/resource_auth0_client_test.go
- auth0/resource_auth0_connection_test.go
- auth0/resource_auth0_custom_domain_test.go
- auth0/resource_auth0_log_stream_test.go
- auth0/resource_auth0_organization_test.go
- auth0/resource_auth0_resource_server_test.go
- auth0/resource_auth0_role_test.go
- auth0/resource_auth0_rule_config_test.go
- auth0/resource_auth0_user_test.go
While running:
```terminal
docker run --rm -v `pwd`:/terraform-provider-auth0 -w /terraform-provider-auth0 golangci/golangci-lint:v1.44.0 golangci-lint run ./...
```
We got a few errors regarding the test sweepers having unchecked errors. This PR refactors that a little bit and ensures we have visibility of any unexpected errors.
We can test that everything still works as expected using the `make test-sweep` command. 
> [1/5] Refactor test sweepers to ensure errors are checked

- auth0/resource_auth0_action.go
- auth0/resource_auth0_hook.go
- auth0/resource_auth0_hook_test.go
Making sure we take care of the last deprecation warnings we got after the terraform plugin sdk v2 upgrade. 
> [2/5] Some more post SDK v2 update deprecation clean up

- auth0/data_source_auth0_client.go
- auth0/data_source_auth0_client_test.go
- auth0/data_source_helpers.go
- auth0/provider_test.go
- auth0/resource_auth0_attack_protection.go
- auth0/resource_auth0_connection.go
- auth0/resource_auth0_global_client.go
- auth0/resource_auth0_role.go
- auth0/resource_auth0_rule.go
Running the below and fixing everything left in the repo. 
```terminal
docker run --rm -v `pwd`:/terraform-provider-auth0 -w /terraform-provider-auth0 golangci/golangci-lint:v1.44.0 golangci-lint run ./...
```
> [3/5] Fix remaining linting issues

- CHANGELOG.md
> Add changelog for v0.30.0

- CHANGELOG.md
> Add changelog for v0.30.3

- .github/workflows/main.yml
- README.md
In this PR we integrate codecov into the project through gh actions using https://github.com/codecov/codecov-action. 
> DXCDT-151 Add codecov

- .golangci.yml
- CONTRIBUTING.md
After all the changes to the testing setup, we're updating the contributing docs with the new details.
We're also reverting the linting rule to ignore dead code. 
- https://github.com/auth0/terraform-provider-auth0/pull/180
- https://github.com/auth0/terraform-provider-auth0/pull/181
- https://github.com/auth0/terraform-provider-auth0/pull/182
- https://github.com/auth0/terraform-provider-auth0/pull/183
- https://github.com/auth0/terraform-provider-auth0/pull/184
> [5/5] [DXCDT-152] Update CONTRIBUTING

- docs/resources/connection.md
Issue #174 highlighted some confusion and guessing around how to configure passwordless email connections. This PR introduces some instruction around how to initially configure along with an example to prevent future confusion.
> Adding documentation for passwordless email connection

- docs/resources/action.md
v3 is now the default version of actions created.
Actions created with v2 are prompted in the console to update.
> Update docs: auth0_action

- .github/workflows/release.yml
Hopefully fixes the issue with the release action:
```
gpg-agent: a gpg-agent is already running - not starting a new one
``` 
> Update gh action release

- auth0/resource_auth0_organization.go
- auth0/resource_auth0_organization_test.go
- auth0/testdata/recordings/TestAccOrganization.yaml
Fix issue with org metadata getting sent as null.
> Fix issue with org metadata getting sent as null

- CHANGELOG.md
> Add Changelog for v0.34.0

- .github/ISSUE_TEMPLATE/feature_request.yml
Renamed about to description as about is not allowed in issue forms.
> Fix issue with feature request issue template

- templates/guides/quickstart.md
In this PR we're adding a Getting Started guide for our provider. We're adding this one in the templates/guides folder and afterwards we'll open another PR after this gets merged to add the generated guide as well within the docs folder.
> DXCDT-199 Add a quickstart guide

- docs/resources/connection.md
- internal/provider/resource_auth0_connection.go
- templates/resources/connection.md.tmpl
> Improve sms and email conn docs

- CHANGELOG.md
> Add Changelog for v0.35.0

- internal/provider/resource_auth0_branding_theme_test.go
- test/data/recordings/TestAccBrandingTheme.yaml
> [1/3] [DXCDT-198] Add tests and recordings for branding themes

- go.mod
- go.sum
- internal/provider/provider.go
- internal/provider/resource_auth0_branding_theme.go
> [3/3] [DXCDT-198] Add new auth0_branding_theme resource

- CHANGELOG.md
> Add changelog for v0.36.0

- .github/ISSUE_TEMPLATE/report_a_bug.yml
Adding a note that the bug should be reported only if still present on the latest version of the provider.
> Update bug template

- CHANGELOG.md
> Add changelog for v0.37.1

- internal/provider/resource_auth0_client_test.go
- internal/provider/resource_auth0_connection_test.go
- test/data/recordings/TestAccClientZeroValueCheck.yaml
- test/data/recordings/TestAccConnection.yaml
- test/data/recordings/TestAccConnectionWithEnabledClients.yaml
Adding additional tests to ensure that work in #320 enables the usage of explicit empty values. These test cases were sourced from #14 which aggregated many related issues around the theme of empty values. Some of these tests were already added in #320 and some weren't directly actionable.
Related Issues:
- https://github.com/alexkappa/terraform-provider-auth0/issues/419
- https://github.com/alexkappa/terraform-provider-auth0/issues/406
- https://github.com/alexkappa/terraform-provider-auth0/issues/382
- https://github.com/alexkappa/terraform-provider-auth0/issues/372
- https://github.com/alexkappa/terraform-provider-auth0/issues/325
- https://github.com/alexkappa/terraform-provider-auth0/issues/322
- https://github.com/alexkappa/terraform-provider-auth0/issues/295
- …
> DXCDT-227: Extended tests for allow empty

- internal/provider/resource_auth0_hook.go
- internal/provider/resource_auth0_hook_test.go
- test/data/recordings/TestAccHook.yaml
- test/data/recordings/TestAccHookSecrets.yaml
> [17/X] Refactor hooks resource to allow for empty fields

- internal/provider/resource_auth0_hook.go
- internal/provider/resource_auth0_hook_test.go
- internal/provider/resource_auth0_log_stream.go
- internal/provider/resource_auth0_log_stream_test.go
- internal/provider/resource_auth0_prompt.go
- internal/provider/resource_auth0_prompt_test.go
- test/data/recordings/TestAccHook.yaml
- test/data/recordings/TestAccHookSecrets.yaml
- test/data/recordings/TestAccLogStreamHTTP.yaml
- test/data/recordings/TestAccLogStreamSumo.yaml
- test/data/recordings/TestAccPrompt.yaml
> [15/X] Refactor log stream resource to allow for empty fields

- internal/provider/resource_auth0_hook.go
- internal/provider/resource_auth0_hook_test.go
- internal/provider/resource_auth0_log_stream.go
- internal/provider/resource_auth0_log_stream_test.go
- internal/provider/resource_auth0_prompt.go
- internal/provider/resource_auth0_prompt_test.go
- internal/provider/resource_auth0_role.go
- internal/provider/resource_auth0_role_test.go
- internal/provider/resource_auth0_rule.go
- internal/provider/resource_auth0_rule_config.go
- internal/provider/resource_auth0_rule_config_test.go
- internal/provider/resource_auth0_rule_test.go
- internal/provider/resource_auth0_user.go
- internal/provider/resource_auth0_user_test.go
- test/data/recordings/TestAccHook.yaml
- test/data/recordings/TestAccHookSecrets.yaml
- test/data/recordings/TestAccLogStreamHTTP.yaml
- test/data/recordings/TestAccLogStreamSumo.yaml
- test/data/recordings/TestAccPrompt.yaml
- test/data/recordings/TestAccRole.yaml
- test/data/recordings/TestAccRule.yaml
- test/data/recordings/TestAccRuleConfig.yaml
- test/data/recordings/TestAccUser.yaml
- test/data/recordings/TestAccUserChangeUsername.yaml
> [13/X] Refactor user resource to allow for empty fields

- internal/provider/resource_auth0_custom_domain.go
- internal/provider/resource_auth0_custom_domain_verification.go
- internal/provider/resource_auth0_hook.go
- internal/provider/resource_auth0_hook_test.go
- internal/provider/resource_auth0_log_stream.go
- internal/provider/resource_auth0_log_stream_test.go
- internal/provider/resource_auth0_prompt.go
- internal/provider/resource_auth0_prompt_test.go
- internal/provider/resource_auth0_role.go
- internal/provider/resource_auth0_role_test.go
- internal/provider/resource_auth0_rule.go
- internal/provider/resource_auth0_rule_config.go
- internal/provider/resource_auth0_rule_config_test.go
- internal/provider/resource_auth0_rule_test.go
- internal/provider/resource_auth0_user.go
- internal/provider/resource_auth0_user_test.go
- test/data/recordings/TestAccHook.yaml
- test/data/recordings/TestAccHookSecrets.yaml
- test/data/recordings/TestAccLogStreamHTTP.yaml
- test/data/recordings/TestAccLogStreamSumo.yaml
- test/data/recordings/TestAccPrompt.yaml
- test/data/recordings/TestAccRole.yaml
- test/data/recordings/TestAccRule.yaml
- test/data/recordings/TestAccRuleConfig.yaml
- test/data/recordings/TestAccUser.yaml
- test/data/recordings/TestAccUserChangeUsername.yaml
> [12/X] Refactor custom domain resource to allow for empty fields

- internal/provider/structure_auth0_tenant.go
- While running real e2e tests we noticed we skipped a few nil checks in the expand funcs on the tenant. We're correcting that with this PR.
> Add missed nil checks for tenant objects

- CHANGELOG.md
> Add changelog for v0.39.0

- .github/workflows/e2e-tests.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/sweep.yml
- .golangci.yml
- go.mod
> Bump go to 1.19

- CHANGELOG.md
> Add changelog for v0.40.0

- CHANGELOG.md
> Add changelog for v0.40.1

- CHANGELOG.md
- docs/resources/connection_client.md
- internal/provider/resource_auth0_connection_client.go
> Add changelog for v0.41.0

- CHANGELOG.md
> Add changelog for v0.42.0

- .github/ISSUE_TEMPLATE/config.yml
> Update help url in issue templates

- internal/provider/resource_auth0_connection_test.go
- internal/provider/structure_auth0_connection.go
- test/data/recordings/TestAccConnectionOkta.yaml
This PR adds support for managin the icon logo url for the Okta conn as requested in #449 .
> DXCDT-355: Add support for managing the icon_url on okta conn

- CHANGELOG.md
> Add changelog for v0.43.0

- CONTRIBUTING.md
- Makefile
- README.md
The main focus of this PR is to give better guidance on how to contribute to the project. To achieve this, several make commands were improved. Additionally the README gets a tiny update as well so it is in line with the format of other SDKs.
> Update contributing guide

- internal/auth0/resourceserver/resource.go
- internal/auth0/resourceserver/resource_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all resource server related resources to their own resource server pkg.
> DXCDT-360: Move resource server to dedicated pkg

- internal/auth0/tenant/data_source.go
- internal/auth0/tenant/data_source_test.go
- internal/auth0/tenant/expand.go
- internal/auth0/tenant/flatten.go
- internal/auth0/tenant/resource.go
- internal/auth0/tenant/resource_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all tenant related resources to their own tenant pkg.
> DXCDT-360: Move tenant resources to dedicated pkg

- internal/auth0/role/resource.go
- internal/auth0/role/resource_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all role related resources to their own role pkg.
> DXCDT-360: Move role resources to dedicated pkg

- internal/auth0/attackprotection/resource.go
- internal/auth0/attackprotection/resource_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all attack protection related resources to their own pkg.
> DXCDT-360: Move attack protection to dedicated pkg

- internal/auth0/client/resource_grant.go
- internal/auth0/client/resource_grant_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all client_grant related resources to the client pkg.
> DXCDT-360: Move client grant resource to client pkg

- internal/auth0/branding/resource.go
- internal/auth0/branding/resource_test.go
- internal/auth0/branding/resource_theme.go
- internal/auth0/branding/resource_theme_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all branding related resources to their own pkg.
> DXCDT-360: Move branding to dedicated pkg

- internal/auth0/hook/expand.go
- internal/auth0/hook/expand_test.go
- internal/auth0/hook/resource.go
- internal/auth0/hook/resource_test.go
- internal/auth0/rule/expand.go
- internal/auth0/rule/expand_test.go
- internal/auth0/rule/resource.go
- internal/auth0/rule/resource_config.go
- internal/auth0/rule/resource_config_test.go
- internal/auth0/rule/resource_test.go
- internal/provider/provider.go
```
.
└── internal/
├── mutex
├── provider
├── auth0/
│   └── ...
├── recorder
├── sweep
├── template
├── validation
└── value
```
We migrate all hook and rule related resources to their own pkg.
> DXCDT-360: Move hook and rule to dedicated pkgs

- docs/guides/action_triggers.md
- docs/guides/quickstart.md
- templates/guides/action_triggers.md
- templates/guides/quickstart.md
Fix yaml frontmatter for doc guides
- https://github.com/auth0/terraform-provider-auth0/blob/main/docs/guides/action_triggers.md
> Fix yaml frontmatter for doc guides

- CHANGELOG.md
> Add changelog for v0.44.0

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/report_a_bug.yml
This PR fixes the labels on our issue templates.
> Update the labels on the issue templates

- CHANGELOG.md
- README.md
- docs/guides/quickstart.md
- templates/guides/quickstart.md
> Add changelog for v0.44.1

- internal/auth0/client/resource_grant.go
- internal/auth0/client/resource_grant_test.go
- test/data/recordings/TestAccClientGrant.yaml
Check if client grant already exists before creating to avoid issues described in #255 
- #255
> issue#255: Check if client grant already exists before creating

- CHANGELOG.md
- README.md
- docs/guides/quickstart.md
- templates/guides/quickstart.md
> Add changelog for v0.45.0

- Makefile
Remove acctest pkg from packages to test and report coverage on as it's a package to setup acc tests for the provider.
> Remove acctest pkg from packages to test and report coverage on

- internal/auth0/action/resource_trigger_binding.go
- internal/auth0/action/resource_trigger_binding_test.go
- test/data/recordings/TestAccTriggerBinding_Import.yaml
When importing an existing trigger binding into terraform state, `trigger` attribute is not set on `auth0_trigger_binding`. This PR fixes that.
- #548
> issue#548: Fix import issue in auth0_trigger_binding

- internal/auth0/connection/resource_clients.go
- internal/auth0/connection/resource_clients_test.go
- test/data/recordings/TestAccConnectionClients.yaml
Follow up from https://github.com/auth0/terraform-provider-auth0/pull/568. 
- https://github.com/auth0/terraform-provider-auth0/pull/568
> [2/2] DXCDT-426: Improve how we guard against erasing unwanted enabled clients

- CHANGELOG.md
- README.md
- docs/guides/quickstart.md
- templates/guides/quickstart.md
> Add changelog for v0.47.0

- MIGRATION_GUIDE.md
> Fix migration guide

- docs/resources/hook.md
- docs/resources/rule.md
- internal/auth0/hook/resource.go
- internal/auth0/rule/resource.go
- templates/resources/hook.md.tmpl
- templates/resources/rule.md.tmpl
Hooks and Rules are deprecated so we're adding a message similar to https://auth0.com/blog/preparing-for-rules-and-hooks-end-of-life/ to help guide users towards a migration path.
> Add deprecation notice for hooks and rules

- internal/auth0/user/resource_roles.go
- internal/auth0/user/resource_roles_test.go
- test/data/recordings/TestAccUserRolesImport.yaml
Similar to https://github.com/auth0/terraform-provider-auth0/pull/594, this fixes an import issue with the `auth0_user_roles` resource.
> Fix import issue on auth0_user_roles

- internal/auth0/hook/expand.go
- internal/auth0/hook/expand_test.go
- internal/auth0/hook/resource.go
- internal/config/config_test.go
- internal/validation/validation_test.go
- internal/value/value_test.go
This PR increases test coverage little.
> Increase test coverage

- MIGRATION_GUIDE.md
- docs/resources/organization_member.md
- examples/resources/auth0_organization_member/resource.tf
- internal/auth0/organization/resource_member.go
Add deprecation notice for org_member roles field now that we introduced a new auth0 org member roles resource.
> [2/2] DXCDT-440: Add deprecation notice for `auth0_organization_member` roles field

- internal/auth0/organization/resource_member_role_test.go
- internal/auth0/organization/resource_member_roles_test.go
- test/data/recordings/TestAccOrganizationMemberRole.yaml
- test/data/recordings/TestAccOrganizationMemberRoles.yaml
Adds import tests for `auth0_organization_member_roles`.
> [7/X] DXCDT-455: Add import tests for auth0_organization_member_roles

- internal/auth0/organization/resource_connection_test.go
- internal/auth0/organization/resource_connections_test.go
- test/data/recordings/TestAccOrganizationConnection.yaml
- test/data/recordings/TestAccOrganizationConnections.yaml
Adds import tests for `auth0_organization_connection`(s).
> [9/X] DXCDT-455: Add import tests for auth0_organization_connection(s)

- .github/workflows/semgrep.yml
Add semgrep github action workflow.
> ASEC-1323: Add semgrep github action workflow

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for rms client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [4/X] DXCDT-441: Reintroduce support for rms client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for slack client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [6/X] DXCDT-441: Reintroduce support for slack client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for sentry client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [7/X] DXCDT-441: Reintroduce support for sentry client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for egnyte client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [9/X] DXCDT-441: Reintroduce support for egnyte client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for office365 client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [12/X] DXCDT-441: Reintroduce support for office365 client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for salesforce client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [13/X] DXCDT-441: Reintroduce support for salesforce client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for layer client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [14/X] DXCDT-441: Reintroduce support for layer client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for springcm client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [17/X] DXCDT-441: Reintroduce support for springcm client addon

- docs/data-sources/client.md
- docs/data-sources/global_client.md
- docs/resources/client.md
- docs/resources/global_client.md
- internal/auth0/client/expand.go
- internal/auth0/client/flatten.go
- internal/auth0/client/resource.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Reintroducing support for wams client addon on the v1 branch after correctly typing them to the new go-auth0 types.
> [18/X] DXCDT-441: Reintroduce support for wams client addon

- .github/workflows/main.yml
- .github/workflows/security.yml
- .github/workflows/sweep.yml
- Makefile
The `-v` flag was removed from the latest version of `govulncheck` so in this PR we are also removing it from the `make check-vuln` command and also taking advantage of the newly introduced officially dedicated govulncheck action from https://github.com/golang/govulncheck-action/tree/v0.2.0 to run our checks. Some further minor tweaks to the github actions workflows were introduced (mainly just making sure we run them on the v1 branch as well).
> Move govulncheck to security workflow

- docs/resources/connection.md
- internal/auth0/connection/schema.go
Description added per what's in Auth0 frontend next to this parameter.
Description of parameter added.
As on attached image.
build run locally, passing
- [ N/A] All new/changed/fixed functionality is covered by tests (or N/A)
- [ N/A] I have added documentation for all new/changed functionality (or N/A)
> Update description of `options.type` within connection resource

- docs/resources/attack_protection.md
- internal/auth0/attackprotection/resource.go
Improve attack protection docs so it's easier to understand what each setting does. Furthermore we're also requiring the enabled property on every block, to prevent blocks from being defined as empty.
> DXCDT-444: Improve attack protection docs

- docs/resources/trigger_actions.md
- docs/resources/trigger_binding.md
- internal/auth0/action/resource_trigger_actions.go
Add `password-reset-post-challenge` to the available trigger bindings.
> Add password-reset-post-challenge to available trigger bindings

- docs/resources/email_provider.md
- examples/resources/auth0_email_provider/import.sh
- examples/resources/auth0_email_provider/resource.tf
- internal/auth0/email/resource.go
- internal/auth0/email/resource_template_test.go
- internal/auth0/email/resource_test.go
- internal/provider/provider.go
Renaming to further explain what the resource does.
> DXCDT-488: Rename auth0_email to auth0_email_provider

- docs/resources/connection.md
- internal/auth0/connection/schema.go
Following up on feedback from https://github.com/auth0/terraform-provider-auth0/issues/724#issuecomment-1641558160.
> Improve metadata_xml docs for saml connections

- docs/resources/log_stream.md
- internal/auth0/logstream/resource.go
Add available options for filtering log streams.
> GH-739: Add available filters to log stream resource

- MIGRATION_GUIDE.md
Fixes the client secret example when reading it from the data source.
> Tiny fix in migration guide

- CHANGELOG.md
- MIGRATION_GUIDE.md
- README.md
- docs/guides/quickstart.md
- templates/guides/quickstart.md
> Add changelog for v1.0.0-beta.0

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
This PR pins the GitHub Workflow action versions.
> ci: Pin GitHub Workflow Actions

- MIGRATION_GUIDE.md
> Update migration guide

- CHANGELOG.md
- MIGRATION_GUIDE.md
> Add changelog for v1.0.0-beta.1

- docs/resources/connection.md
- examples/resources/auth0_connection/resource_with_okta.tf
Fixes incorrect connection resource examples for Okta
https://developer.okta.com/docs/reference/api/oidc/
Setup an Okta connection following the documented example.
- [NA ] All new/changed/fixed functionality is covered by tests (or N/A)
- [NA] I have added documentation for all new/changed functionality (or N/A)
> fix incorrect Okta OIDC endpoints in connection resource examples

- .github/workflows/e2e-tests.yml
- .github/workflows/main.yml
- .github/workflows/security.yml
- .golangci.yml
- go.mod
- internal/config/config.go
Bumps the go version to v1.21 and updates the gh actions workflows accordingly as well.
> Bump go version to 1.21

- CHANGELOG.md
> Add changelog for v1.0.0-beta.2

- CHANGELOG.md
> Add changelog for v0.50.2

- CHANGELOG.md
- MIGRATION_GUIDE.md
> Add changelog for v1.0.0-beta.3

- internal/auth0/connection/expand.go
- internal/auth0/connection/flatten.go
- internal/auth0/connection/flatten_test.go
Adds support for line connection strategy and refactors the flatten func to be similar to the expand. 
- https://github.com/auth0/terraform-provider-auth0/issues/785
> GH-785: Refactor connection options flatten and add line strategy

- internal/auth0/branding/resource.go
- internal/auth0/branding/resource_test.go
- internal/validation/validation.go
- internal/validation/validation_test.go
Adds validation for correct tags on UL template body.
- https://github.com/auth0/terraform-provider-auth0/issues/770
> GH-770: Improve validation for universal login template body

- README.md
Advertising our [Community AMA on September 28](https://community.auth0.com/t/ask-me-anything-with-auth0-terraform-provider/115670).
> Adding community AMA callout to README

- CHANGELOG.md
> Add changelog for v1.0.0-beta.4

- internal/auth0/connection/resource_test.go
- internal/auth0/connection/schema.go
- test/data/recordings/TestAccConnectionOIDC.yaml
- test/data/recordings/TestAccConnectionOkta.yaml
If not provided, the `connection_settings` and `attribute_map` will be set to a default on OIDC and Okta connections, so we're setting this as computed and adjusting the tests.
> Set connection settings and attribute map as computed

- CHANGELOG.md
- README.md
- docs/guides/quickstart.md
- templates/guides/quickstart.md
Updating changelog for upcoming v1.0.0 GA release.
> v1.0.0 Changelog

- README.md
Now that the [Terraform AMA](https://community.auth0.com/t/ask-me-anything-with-auth0-terraform-provider/115670) has come and gone, we should remove the announcement from the readme.
- [Terraform AMA - Auth0 Community Forums](https://community.auth0.com/t/ask-me-anything-with-auth0-terraform-provider/115670)
> Revert Terraform AMA Announcement

- docs/resources/organization_connections.md
- templates/resources/organization_connections.md.tmpl
Fix tiny copy paste issue on the org_conn docs.
> ESD-31822: Update org_conn docs

- docs/resources/email_template.md
- examples/resources/auth0_email_template/resource.tf
The `auth0_email` resource doesn't exist anymore and was renamed to `auth0_email_provider`. The docs for the `auth0_email_provider` still reference `auth0_email`.
> chore(docs): rename auth0_email to auth0_email_provider

- docs/resources/connection.md
- internal/auth0/connection/schema.go
This was specified as the value `auth0` but, according to the api, the actual correct value is `auto`, as shown in the examples as well.
> Fix pkce connection docs typo

- docs/resources/action.md
- internal/auth0/action/resource.go
~This PR adds logic to prevent sending actions secret as empty array if none configured within the resource so they can be managed out of bound without erasing them.~
**Update**:
After careful consideration, we ended up just with an update to the docs advising users to not partially manage secrets.
- #860
> GH-860: Update docs for action secrets

- CHANGELOG.md
> Add changelog for v1.1.0

- docs/data-sources/client.md
- docs/resources/client.md
- docs/resources/tenant.md
- internal/auth0/client/resource.go
- internal/auth0/tenant/resource.go
Update PAR docs to mention that this feature needs to be enabled on the tenant.
> ESD-32774: Update PAR docs

- internal/auth0/client/expand.go
- internal/auth0/client/resource_test.go
- test/data/recordings/TestAccClientAddons.yaml
Allow samlp block to be defined as empty and inherit default values. 
This change will now allow us to define the following:
```terraform
resource "auth0_client" "my_client" {
name        = "Application - Acceptance Test"
description = "Test Applications Long Description"
app_type    = "non_interactive"
addons {
samlp {}
}
}
```
And have the client created with default samlp addon configuration. The defaults are the ones from API V2. 
```json
"samlp": {
"createUpnClaim": true,
"mapUnknownClaimsAsIs": false,
"passthroughClaimsWithNoMapping": true,
"mapIdentities": true,
"signatureAlgorithm": "rsa-sha1",
"digestAlgorithm": "sha1",
"lifetimeInSeconds": 3600,
"nameIdentifierFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
"typedAttributes": true,
"includeAttributeNameFormat": …
```
> ESD-33548: Allow samlp block to be defined as empty and inherit default values

- CHANGELOG.md
> Add changelog for v1.1.2

- CHANGELOG.md
> Add changelog for v1.2.1

- .github/workflows/release.yml
- Pinned the goreleaser version to 1.26.2
> Pinned the goreleaser version to 1.26.2

- CHANGELOG.md
> Add changelog for v1.4.0

- CHANGELOG.md
> Fix changelog for v1.4.0

- docs/resources/prompt_custom_text.md
- internal/auth0/prompt/resource_custom_text.go
Instead of using a hardcoded list of languages, fetch it from a CDN. In case of any failure to retrieve this list, fallback to the hardcoded list.
New docs were successfully generated using the cdn url. No additional tests added.
This is not a breaking change.
> Add support for all languages for Universal Login

- CHANGELOG.md
> Add changelog for v1.6.0

- go.mod
- go.sum
- test/data/recordings/TestAccConnectionAzureAD.yaml
- Updated the TestAccConnectionAzureAD test recording to be compatible with the specified Auth0 SDK version.
- This change ensures that the test suite functions correctly with the updated SDK and resolves any discrepancies between the recording and the expected authentication process.
- Verified that the updated test recording passes in the current CI pipeline.
- Manual testing was conducted to ensure compatibility with the new Auth0 SDK version.
> Fix: Updated `TestAccConnectionAzureAD` test recording

- .gitignore
- CHANGELOG.md
> Version bump to v1.7.3 (and added `dist` directory to .gitignore)

- CONTRIBUTING.md
> Added note on how to sign commits for contribution

- docs/resources/flow.md
- examples/resources/auth0_flow/import.sh
Fix doc:
```sh
terraform import auth0_flow.my_flow "af_qwwwwwwwwwk"
```
> Fix: doc for auth0_flow

- CHANGELOG.md
FEATURES:
- `resource/auth0_token_exchange_profile`: Add a resource for managing Token Exchange Profile ([#1119](https://github.com/auth0/terraform-provider-auth0/pull/1119))
- `data-source/auth0_token_exchange_profile`: Add a data-source for retrieving Token Exchange Profile ([#1119](https://github.com/auth0/terraform-provider-auth0/pull/1119))
ENHANCEMENTS:
- `resource/auth0_client`: Add support to set `token_exchange` property for a client ([#1119](https://github.com/auth0/terraform-provider-auth0/pull/1119))
- `resource/auth0_connection`: Add support to set `authenitcation_methods` and `paskey_options` property for a connection ([#1099](https://github.com/auth0/terraform-provider-auth0/pull/1099))
> Add changelog for 1.11.0

- CHANGELOG.md
> Add changelog for 1.11.1

- docs/resources/prompt_screen_renderer.md
- internal/auth0/prompt/resource_screen_render.go
New screens included in ACUL release-2:
- signup
- login
- password-reset
- password-reset-email
- password-reset-request
- password-reset-success
- password-reset-error
> Include new screens to support ACUL

- CHANGELOG.md
- `resource/auth0_connection`: Add support to set `global_token_revocation_jwt_iss` and `global_token_revocation_jwt_sub` property for a connection ([#1142](https://github.com/auth0/terraform-provider-auth0/pull/1142/))
- `data-source/auth0_user`: Add support to retrieve a user via lucene query ([#1141](https://github.com/auth0/terraform-provider-auth0/pull/1141/))
- `resource/auth0_prompt_partials`: Add support to set prompt as `customized-consent` ([#1151](https://github.com/auth0/terraform-provider-auth0/pull/1151/))
- `resource/auth0_prompt_screen_partial`: Add support to set `form_content` in insertion_points ([#1151](https://github.com/auth0/terraform-provider-auth0/pull/1151/))
- `resource/auth0_prompt_screen_partials`: Add support to set `form_content` in insertion_points …
> Changelog v1.13.0

- docs/resources/prompt_screen_renderer.md
- internal/auth0/prompt/resource_screen_render.go
Support new screens on ACUL as part of release-3:
Prompt-name | Screen-name
-- | --
mfa | mfa-detect-browser-capabilities
mfa | mfa-enroll-result
mfa | mfa-begin-enroll-options
mfa-sms | mfa-country-codes
mfa-email | mfa-email-challenge
mfa-email | mfa-email-list
mfa | mfa-login-options
mfa-push | mfa-push-challenge-push
mfa-push | mfa-push-enrollment-qr
mfa-push | mfa-push-list
mfa-push | mfa-push-welcome
mfa-sms | mfa-sms-challenge
mfa-sms | mfa-sms-enrollment
mfa-sms | mfa-sms-list
> Include new ACUL screens in supported PromptScreenMap List

- CHANGELOG.md
FEATURES:
- `resource/auth0_phone_provider`: Add new resource for managing phone providers ([#1152](https://github.com/auth0/terraform-provider-auth0/pull/1152/))
- `data-source/auth0_phone_provider`: Add a data-source for retrieving phone providers ([#1152](https://github.com/auth0/terraform-provider-auth0/pull/1152/))
- `data-source/auth0_action`: Add a data-source for retrieving action via id/name ([#1139](https://github.com/auth0/terraform-provider-auth0/pull/1139/))
ENHANCEMENTS:
- `resource/auth0_trigger_actions`: Add `custom-phone-provider` and remove `custom-token-exchange` to list of supported triggers ([#1180](https://github.com/auth0/terraform-provider-auth0/pull/1180/))
- `resource/auth0_trigger_action`: Add `custom-phone-provider` and remove `custom-token-exchange` to list of …
> Add changelog for 1.14.0

- CHANGELOG.md
**ENHANCEMENTS**:
- `resource/auth0_connection`: Add support to configure `custom_headers` attribute in Connection Options ([#917](https://github.com/auth0/terraform-provider-auth0/pull/917/))
- `resource/auth0_attack_protection`: Add support to configure `pre_change_password` attribute ([#1196](https://github.com/auth0/terraform-provider-auth0/pull/1196/))
- `resource/auth0_prompt_screen_renderer`: Add support for 12 new screens ([#1191](https://github.com/auth0/terraform-provider-auth0/pull/1191/))
- `resource/auth0_tenant`: Add support to set `rp_logout_end_session_endpoint_discovery` property ([#1192](https://github.com/auth0/terraform-provider-auth0/pull/1192/))
- `resource/auth0_tenant`: Add support to configure `error_page` attribute …
> Add changelog for 1.16.0

- CHANGELOG.md
> Revert back changelog to 1.15.0 HEAD

- CHANGELOG.md
ENHANCEMENTS:
- `resource/auth0_prompt_screen_renderer`: Add support for 14 new screens ([#1226](https://github.com/auth0/terraform-provider-auth0/pull/1226/))
- Add support for dynamic credentials while configuring the provider ([#1172](https://github.com/auth0/terraform-provider-auth0/pull/1172/))  
BUG FIXES:
- `resource/auth0_branding`: Allow setting `font_url` as null ([#1222](https://github.com/auth0/terraform-provider-auth0/pull/1222/)) 
- `resource/auth0_client`: Allow setting `encryption_key` as null ([#1221](https://github.com/auth0/terraform-provider-auth0/pull/1221/))
> Add changelog for 1.18.0

- CHANGELOG.md
FEATURES:
- `resource/auth0_client`: Support Native to Web SSO ([#1231](https://github.com/auth0/terraform-provider-auth0/pull/1231/))
- `resource/auth0_client`: Add support to configure multi Multi-Resource Refresh Token via `policies` ([#1223](https://github.com/auth0/terraform-provider-auth0/pull/1223/))
- 
ENHANCEMENTS:
- `resource/auth0_prompt_custom_text`: Add support for `email-identifier-challenge` prompt ([#1232](https://github.com/auth0/terraform-provider-auth0/pull/1232/))
BUG FIXES:
- `resource/auth0_connection`: Add support to set `realm_fallback` ([#1224](https://github.com/auth0/terraform-provider-auth0/pull/1224/))
- `resource/auth0_connection`: Add validation over `scopes` on Okta Connection ([#945](https://github.com/auth0/terraform-provider-auth0/pull/945/))
> Add changelog for 1.19.0

- internal/auth0/client/expand.go
> Handle nil checks in expand logic for clients

- CHANGELOG.md
- internal/auth0/client/expand.go
BUG FIXES:
- `resource/auth0_client`: Handle null on `session_transfer` and `policies` in refresh_token ([#1237](https://github.com/auth0/terraform-provider-auth0/pull/1237/))
> Add changelog for v1.19.1

- docs/data-sources/action.md
- docs/resources/action.md
- go.mod
- go.sum
- internal/auth0/action/resource.go
- templates/resources/action.md.tmpl
`auth0_action`:  Improved documentation on the behaviour of the `secrets` block. This highlights how the values are stored and modified.  
Closes #1263
> Improve documentation about `secrets` block on `auth0_action`

- CHANGELOG.md
FEATURES:
- Add support for private key JWT authentication ([#1280](https://github.com/auth0/terraform-provider-auth0/pull/1280))
ENHANCEMENTS:
- `resource/auth0_prompt_screen_renderer` : Add support for new screens in Advanced Customization for Universal Login ([#1258](https://github.com/auth0/terraform-provider-auth0/pull/1258))
- `resource/auth0_prompt_custom_text` : Add support for new screens ([#1289](https://github.com/auth0/terraform-provider-auth0/pull/1289))
> Add changelog for v1.23.0

- CHANGELOG.md
ENHANCEMENTS:
- `resource/auth0_prompt_screen_renderer` Add support `filters` and `use_page_template` fields in screen renderer schema. ([#1303](https://github.com/auth0/terraform-provider-auth0/pull/1303))
BUG FIXES:
- `resource/auth0_connection_clients`: Enabled proper handling when removing connection Clients  ([#1304](https://github.com/auth0/terraform-provider-auth0/pull/1304))
> Add changelog for v1.23.1

- docs/resources/log_stream.md
- internal/auth0/client/resource_grant.go
- internal/auth0/logstream/expand.go
- internal/auth0/logstream/flatten.go
- internal/auth0/logstream/resource.go
- test/data/recordings/TestAccOrganizationClientGrant.yaml
`resource:auth0_log_stream`: Added support to configure `startFrom`  param
Closes #1324
> ext: Added support to configure `startFrom` for auth0_log_stream
